### ISSUE TITLE
Margin Caption for Listings

### ISSUE THREAD

**Issue by mskoenz** [fmarotta/kaobook#10]
First off, thx for the amazing template!!

I'm currently trying to copy the caption behavior from figures and tables in the margin, to 
listings as well, but I'm not versed well enogh in latex yet.

I would ideally like to do the follwing and have the caption in the margin:
```
\begin{lstlisting}[caption={My Caption}]
... some code...
\end{lstlisting}
```
I'll post the "workaround" in case I get it working.
Maybe a future enhancement if more people need it?

Cheers
Mario

**Comment by fmarotta** [comment]
Hi Mario,
Thank you for using the template and for sharing this suggestion!

If you are using the template from GitHub, then you should already be able to do exactly what you expected; see for example the following excerpt from the documentation TeX file:
https://github.com/fmarotta/kaobook/blob/10f04defe3c0cc3bdbe47f734708dc7d99a5da15/examples/documentation/chapters/figsntabs.tex#L86-L92
(and the caption is positioned in the margin.) Please let me know if this did not work for you, as I have implemented this feature only recently.

If you are using the template from [latextemplates.com](https://www.latextemplates.com), unfortunately the margin captions for listings are not available yet, but by the end of next week I hope to complete some other modifications and prepare to release the updated version to latextemplates as well.

Cheers,
Federico

**Comment by mskoenz** [comment]
Hi Federico

I just integrated the latest git-version (10f04defe3c0cc3bdbe47f734708dc7d99a5da15) and everything works now as expected, thanks for your detailed answer!

This issue can be closed, since the enhancement is already present.

Cheers Mario
