### ISSUE TITLE
Error when using minted?

### ISSUE THREAD

**Issue by maxdrohde** [fmarotta/kaobook#104]
When I import the minted package, I get this error:

```
Package tocbasic: file extension `lol' cannot be used twice .
```

I'm importing the package like this:
```
\usepackage{minted}
```

**Comment by maxdrohde** [comment]
Also, if I try using minted by uncommenting the line
```
%\RequirePackage{minted}
```
in `kao.sty`, I get many errors.

**Comment by yordiak** [comment]
Have a look [here](https://tex.stackexchange.com/questions/156240/latex-packages-minted-and-scrhack) You may find some guidenace

**Comment by fmarotta** [comment]
Thank you @yordiak. I have now used `\AtEndPreamble` to load scrhack, so now minted can be loaded without problems.
