### ISSUE TITLE
How to change float item names with caption, table 1 as Tab. 1, figure 1 as Fig. 1

### ISSUE THREAD

**Issue by zornli** [fmarotta/kaobook#105]
Dear Marotta,

Usually, I can modify the name in caption by  \renewcommand{\tablename}{Tab.},   \renewcommand{\figurename}{Fig.},  However, it doesn't work in this template. Could please show me how to fix it.

**Comment by fmarotta** [comment]
Dear @zornli,
I can modify the name in the caption exactly in the way you proposed. Where are you writing those commands? Can you please provide a minimal working example? Thank you.
