### ISSUE TITLE
"! LaTeX Error: 'options.sty' not found."

### ISSUE THREAD

**Issue by dwdiehl** [fmarotta/kaobook#106]
This is my first time using this template, and I am also rusty on LaTeX, so apologies if this turns out to be an obvious fix.

Thanks,

Damon

------

When I compile:
 /examples/documentation/main.tex

I receive the error:
! LaTeX Error: 'options.sty' not found.

The directory structure (after the compile attempt) is:
\chapters
glossary.tex
\images
kaobook.cls
main.bib
main.log
main.pdf
main.synctex.gz(busy)
main.tex
\styles

and the \styles directory contents are:
environments.sty
kao.sty
kaobiblio.sty
mdftheorems.sty
packages.sty
plain theorems.sty

-----

I am using the standard build of TeXShop 4.58 on MacOS 11.0.1

My attempts to solve the problem were to search my drive for a misplaced 'options.sty' file (no luck) and to search online for the verbatim error "! LaTeX Error: 'options.sty' not found." (no luck).

**Comment by yordiak** [comment]
Quick thoughts: TeXShop is a front-end editor. It's not a tex distribution. Are you using TexLive or MikTeX or something else? Did you try to update your distribution?

**Comment by AlexanderZeilmann** [comment]
```options``` is a [LaTeX package](https://ctan.org/pkg/options) that you have not installed on your system.
This can have several reasons:
1. Your TeX-Distribution is rather old, i.e., older than the package
2. Did not install the entire TeX-Distribution but only a subset (for example to save storage space).

In the first case, [update your TeX-Distribution](https://tex.stackexchange.com/questions/55437/how-do-i-update-my-tex-distribution).
In the second case, you need to install the package ```options```. If you are on a Mac there is the ```Tex Live Utility```for that.

**Comment by fmarotta** [comment]
I fully endorse the previous comments. Also check out [this reference](https://en.wikibooks.org/wiki/LaTeX/Installing_Extra_Packages) for further instructions on the installation of extra packages.
