### ISSUE TITLE
Header broken in page layout option wide

### ISSUE THREAD

**Issue by berchtth** [fmarotta/kaobook#107]
After updating to the latest version, the following error occurs in the "Page Layout Wide" (\pagelayout{wide}) environment. Only on even pages the page header is broken (see screenshot). 

The error does not occur in older versions. Also not in (\pagelayout{margin}) and not on odd pages.

It is set twoside=true.

Maybe there is a fix or a workaround.
![Bildschirmfoto von 2021-02-22 08-26-42](https://user-images.githubusercontent.com/79442813/108679121-59a4ab80-74ec-11eb-8943-7d704b6d95aa.png)
![Bildschirmfoto von 2021-02-22 08-27-18](https://user-images.githubusercontent.com/79442813/108679125-5ad5d880-74ec-11eb-80a1-6b4652ce3a0d.png)

**Comment by berchtth** [comment]
After some investigation. Older kao.sty with these statements still work as expected. Unfortunately I am not able to debug the dependencies to calculate the appropriate  values in this line for wide pages.
...
\smash{\hspace{-\headmarginparwidth}\hspace{-\headmarginparsep}\makebox[\headtotal][l]{%
...

Older kao.sty definition of Headers.

% Style with chapter number, chapter title, and page in the header (used 
% throughout the document)
\renewpagestyle{scrheadings}{%
	{\hspace{-\marginparwidth}\hspace{-\marginparsep}\makebox[\overflowingheadlen][l]{%
		\parbox[t][1.7cm][c]{2em}{\hfill\thepage}%
		\makebox[2em][c]{\rule[-1.03cm]{1pt}{1.55cm}}%
		\parbox[t][1.7cm][c]{\textwidth}{\leftmark}}}%
	{\makebox[\overflowingheadlen][r]{%
		\parbox[t][1.7cm][c]{\textwidth}{\hfill\rightmark}%
		\makebox[2em][c]{\rule[-1.03cm]{1pt}{1.55cm}}%
		\parbox[t][1.7cm][c]{2em}{\thepage}}}%
	{\makebox[\overflowingheadlen][r]{%
		\parbox[t][1.7cm][c]{\textwidth}{\hfill\rightmark}%
		\makebox[2em][c]{\rule[-1.03cm]{1pt}{1.55cm}}%
		\parbox[t][1.7cm][c]{2em}{\thepage}}}%
}{%
	{}%
	{}%
	{}%
}

**Comment by fmarotta** [comment]
Thanks, you have correctly spotted the source of the problem. When changing page layout to wide, the header would still use the old, margin-layout widths of the margin and of the text. Now I have addedo code so that the widths of the margin and of the text are recalculated every time the page layout is changed, and the problem is solved.

**Comment by berchtth** [comment]
Federico, thanks for the fix, which is almost perfect. However, I think that the header in the "wide" option is moved a bit too far inwards. I hope it can be seen in my screenshot.
![kaobook-wide-2021-03-21 09-57-32](https://user-images.githubusercontent.com/79442813/111899318-204c5680-8a2c-11eb-9ae4-71eec4f567d3.png)

**Comment by fmarotta** [comment]
Thanks, with the next commit the problem should be solved.

**Comment by berchtth** [comment]
Federico, thank you very much for your support solving this issue. One remark for other users. If you change the margin layout figures (e.g. marginparwidth or marginparsep) you have to change also the wide layout (e.g. outer). Sometimes it is a bit of try and error required to get the correct values. As illustration the figures of my document.

% Layout #1: large margins
\newcommand{\marginlayout}{%
	\newgeometry{
		top=27.4\vscale,
		bottom=20.4\vscale,
		inner=24.8\hscale,
		textwidth=111\hscale,
		marginparsep=4.2\hscale,
		marginparwidth=50.4\hscale,
	}%
    \recalchead%
}

% Layout #2: small, symmetric margins
\newcommand{\widelayout}{%
	\newgeometry{
		top=27.4\vscale,
		bottom=27.4\vscale,
		inner=24.8\hscale,
		outer=19.7\hscale,%24.8
		marginparsep=0mm,
		marginparwidth=0mm,
	}%
    \recalchead%
}
