### ISSUE TITLE
! Package scrbase Error: unknown option `pagenumberwidth=2.1em'.

### ISSUE THREAD

**Issue by tbm** [fmarotta/kaobook#109]
I get the following error after updating kaobook:

```
! Package scrbase Error: unknown option `pagenumberwidth=2.1em'.
```

The change was made in 2048120ec12eda29.

Maybe my scrbase is too old? (I'm on Debian 10/stable)

**Comment by bcw** [comment]
I am having the same issue (also on Debian 10/stable), and yes it does appear that an old version of scrbase is the problem. scrbase is part of KOMA-Script (which this project uses), and `texdoc koma-script` (or more specifically, `texdoc scrguien`) on Debian shows the version as 3.25. Searching for `pagenumberwidth` there gives no results, but [the latest documentation](http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/koma-script/doc/scrguien.pdf), linked from [the CTAN page](https://www.ctan.org/pkg/koma-script), tells me it's there; but only from version 3.27.

I don't know enough about TeX programming to fix this issue myself, and Debian (and any others still using the old code) may upgrade their version after a while anyway, but it would be nice if some conditional code to check for this feature could be added in the meantime...

**Comment by fmarotta** [comment]
You are right, I have now added a check so that the `pagenumberwidth` option is used only if scrbase is at least version 3.27. Could you please confirm that now there are no errors? Thank you.

**Comment by tbm** [comment]
Now I get:

```
! Undefined control sequence.
\mainmatter ->\Ifthispageodd 
                             {\afterpage {\blankpage }}{}\oldmainmatter \pag...
l.54 \mainmatter
                
? 
```

**Comment by tbm** [comment]
If I revert b3f57c979cc42ac4b it works.

**Comment by fmarotta** [comment]
I have added a version check for that as well.

**Comment by tbm** [comment]
Thanks it works now!
