### ISSUE TITLE
minted support possible

### ISSUE THREAD

**Issue by mskoenz** [fmarotta/kaobook#11]
Minted is an alternative package for listings, and I would like to have the captions in the margins as well, as for the "normal" listings.
```
\usepackage[outputdir=build]{minted}

...

\begin{listing} % a command from minted, not to be confused with lstlisting
\begin{minted}{python}
import numpy as np
\end{minted}
\caption{Awesome}
\end{listing}
```
Support can be achieved by copying the two sections in `kao.def`
```
\floatsetup[lstlisting]{
...
}
```
each right underneath each other and changing lstlisting to listing, ending up with:
```
\floatsetup[lstlisting]{
...
}
\floatsetup[listing]{
...
}
```

I'm not sure if this is something the template should handle, since not everyone wants minted imported, and sniffing if it is imported and then adding these lines could result in nasty include dependency errors? Again, my latex-skills are basic, but I assume this kind of plugin issue is the same there.

I will leave it up to the author to close this issue without action, since I dont really see need, just posting it for fellow writer with the same issue/question.

Used version: (10f04defe3c0cc3bdbe47f734708dc7d99a5da15)

**Comment by fmarotta** [comment]
Hi Mario,

This is a good point, I think that the template should handle this as I know for sure that other users are interested in the minted package. Luckily, having a `\floatsetup` for minted's listing without importing minted itself is not harmful at all, so I will implement your solution right away.

Thanks!

**Comment by mskoenz** [comment]
Perfect, happy to have it, thx!
