### ISSUE TITLE
Add .github folder with "community health files"

### ISSUE THREAD

**Issue by AlexanderZeilmann** [fmarotta/kaobook#112]
GitHub allows adding a ```.github``` folder with so-called  [community health files](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file).
These are things like:
* CODE_OF_CONDUCT.md
* CONTRIBUTING.md
* FUNDING.yml
* Issue and pull request templates and config.yml
* SECURITY.md  (We probably don't need that one)
* SUPPORT.md

I think especially the issue templates would be very helpful for kaobook. I can send a pull request for this if you want.

**Comment by fmarotta** [comment]
Yeah, great idea. A PR would be excellent!

P.S. I hope to start working on a package for CTAN as soon as possible. Somehow I keep procrastinating this :/

**Comment by fmarotta** [comment]
Regarding the sponsorship, I am happy to accept one-time donations, but I don't think I will apply to the GitHub sponsorship program: for me, kaobook is a 'side project,' and I don't want to feel pressured to work on it when I have other duties

**Comment by AlexanderZeilmann** [comment]
I can completely understand this. I did not know that there is this ongoing payment thing. I thought this is always a one-time payment 🙈
