### ISSUE TITLE
Automatic margin text alignment in twoside mode

### ISSUE THREAD

**Issue by lutai14** [fmarotta/kaobook#119]
## Summary

Automatic margin text alignment in twoside mode

## Details

I'm working on my thesis in twoside mode. The paper would be much more visually appealing if the margin text could automatically align towards the center depending on even/odd pages.

**Comment by fmarotta** [comment]
Mmm, sorry but what do you mean? Is it maybe that the baseline of the text in the margin is not aligned with the baseline of the text in the body? Does it happen also in oneside mode?
