### ISSUE TITLE
Margin Listings Support

### ISSUE THREAD

**Issue by mskoenz** [fmarotta/kaobook#12]
Sry for again proposing something ^^

I really like the `\margintable` and `\marginfigure` and needed the same for listings, since it would be ideal for shorter example code or small summary listings.

So I modified `kao.def` and added
```
% Environment to hold a margin listing (from the sidenotes package)
\newsavebox{\@sidenotes@marginlistingbox}
\newenvironment{marginlisting}[1][0pt]{ % The optional parameter is the vertical offset
    \FloatBarrier % Force LaTeX to place previous floats
    \mparshift{\snotez@if@nblskip{#1}{\@cdr#1\@nil\baselineskip}{#1}} % Move the listing up or down according to the offset argument
    \begin{lrbox}{\@sidenotes@marginlistingbox}
        \begin{minipage}{\marginparwidth}
            %\captionsetup{type=listing,style=marginlisting}
            \captionsetup{type=listing}
            \centering
}{
        \end{minipage}
    \end{lrbox}
    \marginpar{\usebox{\@sidenotes@marginlistingbox}} % Place the listing box in the margin
}
```
right after the margin table definition. Really the only thing that's different is that it should say Listing X.Y instead of Table X.Y.

This works for "normal" listings:

```
\begin{marginlisting}
    \caption{Awesome Code}
    \begin{lstlisting}{bash}
        ls -la
    \end{lstlisting}
\end{marginlisting}
```

and for minted listings:

```
\begin{marginlisting}
    \caption{Awesome Code}
    \begin{minted}{bash}
        ls -la
    \end{minted}
\end{marginlisting}
```

Again, I just post it here if somebody else needs it and leave it up to the author if this is an enhancement or would just bloat the template...

**Comment by fmarotta** [comment]
Great job!

Since you have already the code feel free to make a pull request, otherwise I will update the file tomorrow.

**Comment by mskoenz** [comment]
Created pull request #13
