### ISSUE TITLE
Chapter without \setchapterimage shows previous image

### ISSUE THREAD

**Issue by tbm** [fmarotta/kaobook#121]
This is a recent regression.

Let's say you have a chapter that uses `\setchapterimage`.  After this chapter is one that does *not* set an image.  Previously no image was shown for that chapter.  Now the previous image's chapter is used.

A test case is on the last page of https://github.com/tbm/kaobook-testcase

**Comment by tbm** [comment]
Reverting 1a8c6a16 brings back the old behaviour.

**Comment by fmarotta** [comment]
Wait, I think that in versions before 1a8c6a16bbea6b881fd5324537e6de8bccd16e65, while the chapter image is not displayed, the gray rectangle is still there. In my opinion having the gray rectangle without the figure is a bug (which I wasn't aware of, by the way), while repeating the image of the previous chapter is acceptable. After all, also the other `chapterstyle` commands maintain their effect until a new style is chosen, so I believe it makes sense that, if you don't want an image in the next chapter, you have to explicitly call `\setchapterstyle{plain}` before that chapter, just like you have to call it to "revert" from the `kao` chapter style. But still, setting the chapter image "one-off" shouldn't be too difficult a modification to do, so I'll think about it. If other users have thoughts on this subject, I'll be happy to start a new discussion or read more posts in this issue.

**Comment by tbm** [comment]
You make some good points, but I just wanted to comment on this:

> In my opinion having the gray rectangle without the figure is a bug (which I wasn't aware of, by the way)

To me this behaviour made sense.  If there's no image for a chapter, I want the gray rectangle (without an image) because I want the same chapter style for the same document.  I think switching between the image style and plain would look quite weird. while repeating the image of the previous chapter is acceptable

So if you want to repeat the previous image instead of showing no image, I think that's fine.  But in this case I think there should be some kind of option to signal that I want no photo (i.e. the gray rectangle only) for those who like consistency.

**Comment by fmarotta** [comment]
With the latest commit, `\setchapterimage` automatically sets the chapter style with the gray rectangle, and if no image is specified for the next chapter, the gray rectangle persists, without any images. I have also added a new, independent chapter style for the gray rectangle, so if you now write `\setchapterstyle{bar}` you can have the gray bar without having to set the chapter image. Thus,
1) You can have the gray-bar chapter style anytime by writing `\setchapterstyle{bar}`.
2) If you want a chapter image, write `\setchapterimage{path/to/image}`: the gray-bar chapter style will be automatically used for that and subsequent chapters, until it is changed again with `\setchapterstyle`. But subsequent chapters won't have the image of the previous chapter.

**Comment by tbm** [comment]
That sounds great to me, thanks @fmarotta!
