### ISSUE TITLE
[Q]: Does \textcitecolor or \parencitecolor still exist?

### ISSUE THREAD

**Issue by yordiak** [fmarotta/kaobook#122]
Hello,

If I recall correctly, you have implemented a command for coloring the whole authors in citations and not only the year. Are these command still exist in your latest version or you have remove them, because I cannot find them in `kaobiblio.sty`

**Comment by fmarotta** [comment]
I don't remember these commands, but I do have a terrible memory... I am pretty sure that now they don't exist, so I'll try to re-implement them. Are you using the "authoryear" style? If so, would you like the authors to be coloured only in the reference that is displayed in the margin, or also in citation within the main text?

**Comment by yordiak** [comment]
Maybe it's my mistake. I m using author-year and I want the authors to be colored in the main text (I don't use neither `\sidecite` nor `\margincite` command)

**Comment by fmarotta** [comment]
To define `\textcitecolor` and `\parencitecolor` you can add the following code, adapted from [here](https://tex.stackexchange.com/questions/15951/hyperlink-name-with-biblatex-authoryear-biblatex-1-4b), to the preamble (or to `kaobiblio.sty`, if you prefer)

```
\DeclareFieldFormat{textcitehyperref}{%
  \DeclareFieldAlias{bibhyperref}{noformat}% Avoid nested links
  \bibhyperref{%
    #1%
    \ifbool{cbx:parens}
      {\bibcloseparen\global\boolfalse{cbx:parens}}
      {}}}
\newbibmacro*{textcitecolor}{%
  \ifboolexpr{
    ( not test {\iffieldundef{prenote}} and 
      test {\ifnumequal{\value{citecount}}{1}} )
    or  
    ( not test {\iffieldundef{postnote}} and 
      test {\ifnumequal{\value{citecount}}{\value{citetotal}}} )
  }
    {\DeclareFieldAlias{textcitehyperref}{noformat}}
    {}% 
  \printtext[textcitehyperref]{%
    \usebibmacro{textcite}}}
\DeclareCiteCommand{\textcitecolor}
  {\boolfalse{cbx:parens}}
  {\usebibmacro{citeindex}%
   \iffirstcitekey
     {\setcounter{textcitetotal}{1}}
     {\stepcounter{textcitetotal}%
      \textcitedelim}%
   \usebibmacro{textcitecolor}}
  {\ifbool{cbx:parens}
     {\bibcloseparen\global\boolfalse{cbx:parens}}
     {}}
  {\usebibmacro{textcite:postnote}}

\DeclareFieldFormat{citehyperref}{%
  \DeclareFieldAlias{bibhyperref}{noformat}% Avoid nested links
  \bibhyperref{#1}}
\newbibmacro*{citecolor}{%
    \printtext[citehyperref]{%
        \usebibmacro{cite}}%
}
\DeclareCiteCommand{\parencitecolor}[\mkbibparens]
  {\usebibmacro{prenote}}%
  {\usebibmacro{citeindex}%
   \usebibmacro{citecolor}}
  {\multicitedelim}
  {\usebibmacro{postnote}}
```

However, the fact that the author name is not a hyperlink bothers more than one biblatex user (see, e.g., [this issue](https://github.com/plk/biblatex/issues/428)). Therefore I have decided to add an option to kaobiblio to automatically convert everything to a hyperlink in the default citation commands. In particular, passing the option `linkeverything=true` to kaobiblio when loading it with the authoryear style will make the author name a hyperlink, like the year. The `linkeverything` option should works also for other styles like authoryear-* and authortitle-*, but use it at your own risk. Note that `linkeverything` affects the default citation commands like `\cite` and `\parencite`, it does not define `\parencitecolor`.

**Comment by yordiak** [comment]
I really love the `linkeverything` option. For my needs this command does the job!

**Comment by yordiak** [comment]
However, I found a bug. I am using authoryear-comp. If the `linkeverything=true`, then the `textcite{author2000,author2001}` produces author(2000),2001, whereas if `linkeverything=false`, then the `textcite{author2000,author2001}` produces author(2000;2001)
