### ISSUE TITLE
Margin citation to have web link

### ISSUE THREAD

**Issue by km5es** [fmarotta/kaobook#125]
Is there a way I can have web links embedded in the margin citation? So that one could click on, say, the title and be directed to the web page? Aaron Turon has that in his thesis and I would like to replicate it:

http://aturon.github.io/academic/turon-thesis.pdf

Here's a screenshot:

![image](https://user-images.githubusercontent.com/35708022/113326876-3ee20580-92e8-11eb-8db0-faf9ba4430b6.png)

Clicking on the year takes you to the bib entry, and clicking on the title links you to the DOI. I would prefer to use the url entry from main.bib instead.

This is a great template, BTW. Thanks a lot for making it, I really appreciate it, and am planning to use it for my PhD thesis.

Cheers.

**Comment by yordiak** [comment]
Did you tried something like `\href{the link}{\marginside{bibtex key}}`?

**Comment by fmarotta** [comment]
Very interesting! Try adding this to the preamble of your main.tex:
```
\RenewDocumentCommand{\formatmargincitation}{m}{
    \DeclareFieldFormat{citeurl}{\href{#1}{\citetitle{#1}}}% make \citeurl outut the title as a hyperlink
    \parencite{#1}: \citeauthor*{#1} (\citeyear{#1}), \citeurl{#1}%
    \DeclareFieldFormat{citeurl}{\url{#1}}% revert the change
}
```

Note that this assumes that your entries in the .bib files have the 'url' field.

**Comment by km5es** [comment]
No, that doesn't quite work. It does not make the link clickable in the Overleaf editor. If I download it and open it with a pdf client (like Foxit) it tries to open the title of the bib reference as a link not the url entry. So for example, the bib entry:

```
@article{Zou2005,
abstract = {We propose the elastic net, a new regularization and variable selection method. Real world data and a simulation study show that the elastic net often outperforms the lasso, while enjoying a similar sparsity of representation. In addition, the elastic net encourages a grouping effect, where strongly correlated predictors tend to be in or out of the model together. The elastic net is particularly useful when the number of predictors (p) is much bigger than the number of observations (n). By contrast, the lasso is not a very satisfactory variable selection method in the p≫n case. An algorithm called LARS-EN is proposed for computing elastic net regularization paths efficiently, much like algorithm LARS does for the lasso.},
author = {Zou, Hui and Hastie, Trevor},
doi = {10.1111/j.1467-9868.2005.00503.x},
journal = {J. R. Stat. Soc.},
keywords = {grouping effect,lars algorithm,lasso,p,penalization},
number = {2},
pages = {301--320},
pmid = {20713001},
title = {{Regularization and variable selection via the elastic-net}},
volume = {67},
year = {2005},
url={https://www.google.com/}
}
```
will try to open /local_path/Zou2005.pdf

P.S. I copied that code snippet into main.tex just before `\begin{document}`. Please let me know if that's wrong.

**Comment by fmarotta** [comment]
Sorry, I made a typo. Could you give the following snippet a try?
```
\RenewDocumentCommand{\formatmargincitation}{m}{
    \DeclareFieldFormat{citeurl}{\href{##1}{\citetitle{#1}}}% make \citeurl outut the title as a hyperlink
    \parencite{#1}: \citeauthor*{#1} (\citeyear{#1}), \citeurl{#1}%
    \DeclareFieldFormat{citeurl}{\url{##1}}% revert the change
}
```
It works for me with the latest kaobook version uploaded on Overleaf: I edited main.bib so that the reference 'James2012' points to 'https://www.google.com'.
![image](https://user-images.githubusercontent.com/26001460/120598103-273d0f80-c446-11eb-9ba5-d04ef2e37ad8.png)

**Comment by km5es** [comment]
Thanks. This works great now. I appreciate your help.

On a related note: how do I get rid of the URL info in the bibliography? Right now it is showing the entire link which is taking up too much space.

**Comment by fmarotta** [comment]
Try adding this to your main.tex:
```
\AtEveryBibitem{
    \clearfield{url}
}
```
