### ISSUE TITLE
Footnotes not in superscript

### ISSUE THREAD

**Issue by BenzoX** [fmarotta/kaobook#132]
Hi! First, many thanks for your work on this class, it is wonderful for writing my thesis.
While I extensively use sidenotes, I happen to have footnotes here and there (for puns and similar content). However, the footnote mark is not displayed in superscript. Here is a MWE (attached is the output pdf):
`\documentclass{kaobook}
\begin{document}
This is some footnote test\footnote{This is a test for \texttt{footnote}}.
\end{document}
`
[mwe.pdf](https://github.com/fmarotta/kaobook/files/6290010/mwe.pdf)
Is this a bug or a feature? In the former case, do you have an idea on how to solve this problem?
Thanks!

**Comment by AlexanderZeilmann** [comment]
Hmm, your example code is not compiling on my machine.

The following code compiles and puts the footnote mark in the superscript as expected:
```
\documentclass{kaobook}

\usepackage[english]{babel}
\usepackage{kaobiblio}
\usepackage{kaotheorems}
\usepackage{kaorefs}

\begin{document}
This is some footnote test\footnote{This is a test for \texttt{footnote}}.
\end{document}
```

Can you try again, and if the issue persists check whether your LaTeX version and your kaobook version are up to date?

**Comment by BenzoX** [comment]
This indeed looks like an updating issue. Sorry about that, I should have checked more carefully the versions of all packages. Thank you for you reply!
