### ISSUE TITLE
Package babel Error: You haven't defined the language italian yet.

### ISSUE THREAD

**Issue by fbob** [fmarotta/kaobook#14]
From a raw report-template.tex
Don't know if I've missed something in my latex config 
 
```
! Package babel Error: You haven't defined the language italian yet.

See the babel package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.80 \iflanguage{italian}
                         {
)
! Emergency stop.
<*> kaobiblio.sty
```

**Comment by fmarotta** [comment]
Thank you for reporting this. It appears that the `\iflanguage` macro fails if the language pack being tested is not installed, and I believe that this is what happened in your case.

I will soon push a new version where the problem should be fixed. Please let me know if there are still errors.

**Comment by fbob** [comment]
Thanks !
:+1:
