### ISSUE TITLE
Reduce depth of marginTOC only

### ISSUE THREAD

**Issue by lutai14** [fmarotta/kaobook#140]
I would like to reduce the depth of the margintoc but keep the current depth of the normal toc. In other words, I want:
- My toc to show chapters, sections and subsection
- The margintoc's to stop at the sections 

Is this achievable given the current implementation of the package?

**Comment by AlexanderZeilmann** [comment]
Do I understand you correctly?
Currently, the margintoc shows `sections` and `subsections`.
You only want it to show `sections`.

If this is the case, add
```
\setcounter{margintocdepth}{\sectiontocdepth}
```
somewhere in your preamble.
