### ISSUE TITLE
[Q]: Long title in kao chapter style

### ISSUE THREAD

**Issue by yordiak** [fmarotta/kaobook#145]
`kaobook` default setting cannot properly handle long chapters titles, causing them to swift on the top of the paper. Thus, I would be grateful if you could tell me which line of code should I modify in order to increase the linewidth of chapter's title in the `kao` chapter style

**Comment by AlexanderZeilmann** [comment]
Hmm, what do you mean by "swift on top of the paper"?

For me, long chapter titles look okay:

<img width="1005" src="https://user-images.githubusercontent.com/901391/119952836-b1482c80-bf9d-11eb-9443-bdce8645c817.png">

```
\setchapterstyle{kao}
\setchapterpreamble[u]{\margintocshort}
\chapter{This is a very long chapter title that wraps to the next line and a third line also looks ok}
\blindtext
\section{Lorem ipsum}
\section{Dolor sit}
```

Adding a fourth line looks ugly and after adding a fifth line, the first line is not shown any longer.

**Comment by yordiak** [comment]
The commands
```
\setchapterpreamble[u]{\margintoc}
\chapter{Using the goal-framing theory to determine organic production choices\footnotemark{}}\footnotetext{test}
\labch{ver_int}
```
produces 
![image](https://user-images.githubusercontent.com/21086323/119998313-4288c480-bfd9-11eb-846c-e23bd624fdda.png)

**Comment by AlexanderZeilmann** [comment]
Can you post a minimal example of an entire document?

I get different line breaks (also with `twoside = true`, `open = any` and `LuaHBTeX, Version 1.13.2 (TeX Live 2021)`):
<img width="1153" alt="Bildschirmfoto 2021-05-28 um 16 39 05" src="https://user-images.githubusercontent.com/901391/120000552-3ac62180-bfd3-11eb-82ce-d5d0cbeaa0c4.png">

**Comment by yordiak** [comment]
```
\documentclass[
	a4paper, % Page size
	fontsize=12pt, % Base font size
    twoside=true, % Use different layouts for even and odd pages (in particular, if twoside=true, the margin column will be always on the outside)
	open=any, % If twoside=true, uncomment this to force new chapters to start on any page, not only on right (odd) pages
	%chapterentrydots=true, % Uncomment to output dots from the chapter name to the page number in the table of contents
	numbers=noenddot, % Comment to output dots after chapter numbers; the most common values for this option are: enddot, noenddot and auto (see the KOMAScript documentation for an in-depth explanation)
]{kaobook}

%--------------------------------------------------------------------------------
%	PACKAGES AND OTHER DOCUMENT CONFIGURATIONS
%--------------------------------------------------------------------------------

% Choose the language
\usepackage[libertinus]{fontsetup}
\usepackage{polyglossia}

\setmainlanguage{english}
\setotherlanguage{greek}

\usepackage[english=british]{csquotes}	% English quotes

% Load the bibliography package
\usepackage[backend=biber,linkeverything=false,maxcitenames=2]{styles/kaobiblio}
\renewcommand{\formatmargincitation}[1]{
 \citeauthor*{#1} (\citeyear{#1}): {\citetitle{#1}}.  
}

\renewbibmacro{in:}{} % Supress ``In''
\renewcommand*{\nameyeardelim}{\addcomma\space} %Add comma

% Load mathematical packages for theorems and related environments. 
\usepackage{styles/mdftheorems}
\usepackage{physics}

\DeclareMathOperator*{\argmax}{\arg\!\max}
\DeclareMathOperator*{\argmin}{\arg\!\min}

% Load mathematical packages for theorems and related environments. NOTE: choose only one between 'mdftheorems' and 'plaintheorems'.
\usepackage{styles/mdftheorems}

% Load the package for hyperreferences
\usepackage{styles/kaorefs}

% Reset sidenote counter at chapters
%\counterwithin*{sidenote}{chapter}
\counterwithout{sidenote}{chapter}

\begin{document}
\setchapterstyle{kao}
\setchapterpreamble[u]{\margintoc}
\chapter{Using the goal-framing theory to determine organic production choices\footnotemark{}}\footnotetext{test}
\labch{ver_int}
\end{document}
```

**Comment by AlexanderZeilmann** [comment]
From the fact, that the `kao` libraries are in the `styles` folder I assume that you are using an old version of `kao`. Can you check whether `kao` is up to date?

**Comment by yordiak** [comment]
I just download the latest kaobook version (0.9.6) and the problem is even worse (the first line is disappeared). I am using MikTeX 21.3

**Comment by AlexanderZeilmann** [comment]
Ah yes, I was using `fontsize=10pt`, so the title fits nicely.

I think if the chapter starts on a right page everything is working as it should.
See the following screenshot, where the title is as wide as the text body below.
(The screenshot uses `\usepackage{showframe}` to  highlight the bounding boxes.)

![Bildschirmfoto 2021-05-28 um 23 17 49](https://user-images.githubusercontent.com/901391/120042726-f35b8780-c00a-11eb-88b3-235ee8668395.png)


On chapters that start on a left page the title also are as wide as the body. 
However, the chapter number should be on the other margin. This is bug #144 but is unrelated to your problem.

![Bildschirmfoto 2021-05-28 um 23 14 25](https://user-images.githubusercontent.com/901391/120042483-75977c00-c00a-11eb-8f04-308a8e5a74b2.png)

So I think there cannot be done much about the line width and `kao` is working as expected.

An idea might be to extend the title vertically downwards if required. But I currently have no idea how to implement this and then the title pages would look inconsistent.

**Comment by yordiak** [comment]
I think a solution would be a redefinition of `\chapter` command in which the width of the text might be explicitly defined. For instance, chapters might use the `wide` paper style (as in parts) instead of the `margin`.

**Comment by fmarotta** [comment]
@yordiak, would you expand the chapter title to the left, right, or both? You can expand it to the right with something like this:
```
\setlength{\textwidth}{1.3\textwidth}
\recalchead
\chapter{Using the goal-framing theory to determine organic production 
choices\footnotemark{}}\footnotetext{test}
\setlength{\textwidth}{0.769\textwidth} % revert the change
\recalchead
```

However, I tend to like when everything is aligned so if I were in your situation I'd try to find an alternative solution. For instance, enlarging the text width for the whole document (and not just for the chapter title), use a smaller font, or manually insert linebreaks in convenitent positions (e.g. `...determine organ-\\ ic production choices`). If you want to fiddle with the lengths used for chapter titles, unfortunately it's not just one line of code :( you can find everything in `kaobook.cls` by searching for this line: `\DeclareDocumentCommand{\chapterstylekao}{}{%`. This command takes care of the formatting of the chapter titles. I can help if you want to expand the title to the left or in both directions.

**Comment by yordiak** [comment]
@fmarotta Thanks for the recommendation.

The problem appears if for some reason (either by definition or manually) chapter title split to multiple lines, especially more than 3 lines. As @AlexanderZeilmann points, the title is aligned to the main body. However, I don't think that it would look ugly if the title was aligned to the margintoc instead of the body. 

Another recommendation would be that in cases where the title exceeds the 3 line limit, then the main body of the document should move a little bit lower.

Thanks again for your comments/recommendations

**Comment by fmarotta** [comment]
You can try to add this to the preamble of the main.tex:
```
\RenewDocumentCommand{\chapterstylekao}{}{%
    \renewcommand*{\chapterformat}{%
        \mbox{\chapappifchapterprefix{\nobreakspace}\scalebox{2.85}{\thechapter\autodot}}%
    }%  
    \renewcommand\chapterlinesformat[3]{%
        \vspace{3.5\vscale}%
        \if@twoside%
            \Ifthispageodd{%
                \smash{\makebox[0pt][l]{%
                    \parbox[b]{\textwidth + \marginparwidth}{\flushright{##3}}%
                    \makebox[\marginparsep][c]{\rule[-2\vscale]{1pt}{27.4\vscale+\f@size mm}}%
                    \parbox[b]{0pt}{##2}%
                }}%
            }{
                \smash{\makebox[\textwidth][r]{%
                    \parbox[b]{\widthOf{##2}}{\flushright{##2}}%
                    \makebox[\marginparsep][c]{\rule[-2\vscale]{1pt}{27.4\vscale+\f@size mm}}%
                    \parbox[b]{\textwidth + \marginparwidth}{\flushleft{##3}}%
                }}%
            }
        \else%
            \smash{\makebox[0pt][l]{%
                \parbox[b]{\textwidth + \marginparwidth}{\flushright{##3}}%
                \makebox[\marginparsep][c]{\rule[-2\vscale]{1pt}{27.4\vscale+\f@size mm}}%
                \parbox[b]{0pt}{##2}%
            }}%
        \fi%
    }%  
    \RedeclareSectionCommand[beforeskip=0cm,afterskip=10\vscale]{chapter}%
    \setlength{\mtocshift}{-3\vscale}%
}
```
It will increase the width of the chapter title only, making it take the full page width.

**Comment by yordiak** [comment]
I am getting an error:
```
! Undefined control sequence.
<argument> \f 
```

**Comment by fmarotta** [comment]
Sorry, I forgot to mention that you should wrap the code in `\makeatletter` - `\makeatother`, like so:
```
\makeatletter
\RenewDocumentCommand{\chapterstylekao}{}{%
    \renewcommand*{\chapterformat}{%
        \mbox{\chapappifchapterprefix{\nobreakspace}\scalebox{2.85}{\thechapter\autodot}}%
    }%  
    \renewcommand\chapterlinesformat[3]{%
        \vspace{3.5\vscale}%
        \if@twoside%
            \Ifthispageodd{%
                \smash{\makebox[0pt][l]{%
                    \parbox[b]{\textwidth + \marginparwidth}{\flushright{##3}}%
                    \makebox[\marginparsep][c]{\rule[-2\vscale]{1pt}{27.4\vscale+\f@size mm}}%
                    \parbox[b]{0pt}{##2}%
                }}%
            }{
                \smash{\makebox[\textwidth][r]{%
                    \parbox[b]{\widthOf{##2}}{\flushright{##2}}%
                    \makebox[\marginparsep][c]{\rule[-2\vscale]{1pt}{27.4\vscale+\f@size mm}}%
                    \parbox[b]{\textwidth + \marginparwidth}{\flushleft{##3}}%
                }}%
            }
        \else%
            \smash{\makebox[0pt][l]{%
                \parbox[b]{\textwidth + \marginparwidth}{\flushright{##3}}%
                \makebox[\marginparsep][c]{\rule[-2\vscale]{1pt}{27.4\vscale+\f@size mm}}%
                \parbox[b]{0pt}{##2}%
            }}%
        \fi%
    }%  
    \RedeclareSectionCommand[beforeskip=0cm,afterskip=10\vscale]{chapter}%
    \setlength{\mtocshift}{-3\vscale}%
}
\makeatother
```
