### ISSUE TITLE
`LaTeX Warning: Unused global option(s):     [secnumdepth=1].`

### ISSUE THREAD

**Issue by goretkin** [fmarotta/kaobook#149]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description
Examples mention `secnumdepth=1`, e.g.
https://github.com/fmarotta/kaobook/blob/b26491ef4a533f4920b8141d345d90b931436e4a/examples/minimal_book/main.tex#L6

but LaTeX warns:

```
LaTeX Warning: Unused global option(s):
    [secnumdepth=1].
```

### Minimal Working Example
```latex
\documentclass[
	secnumdepth=1, % How deep to number headings. Defaults to 1 (sections)
]{kaobook}

\begin{document}
\mainmatter


\end{document}
```

### Additional Information

```
$ pdflatex --version
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021)
kpathsea version 6.3.3
Copyright 2021 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.03
```

**Comment by fmarotta** [comment]
Thanks, I was using an external package to handle custom options like `secnumdepth`, but now I am using the official KOMAScript way and the warning is gone.
