### ISSUE TITLE
Turn _ into \_ in  introduction.tex in documentation

### ISSUE THREAD

**Issue by callegar** [fmarotta/kaobook#154]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description

Documentation does not compile cleanly. In file `examples/documentation/chapters/introduction.tex` you have `\Path{./examples/minimal_book/main.tex}` which should be `\Path{./examples/minimal\_book/main.tex}` because this is not a verbatim env.

**Comment by fmarotta** [comment]
Fixed, thank you!
