### ISSUE TITLE
Wrong PDF bookmarks hierarchy

### ISSUE THREAD

**Issue by cgosorio** [fmarotta/kaobook#155]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description

The change introduced in issue #101 has introduced an undesired side effect and now the PDF Bookmark hierarchy is incorrect. You get something like (with certain elements duplicated and weird nesting):
![image](https://user-images.githubusercontent.com/7659408/121772951-1ba1c500-cb79-11eb-86d5-e4e2d2d410c8.png)

Instead of the correct one:
![image](https://user-images.githubusercontent.com/7659408/121772960-3116ef00-cb79-11eb-9f57-f88b1079a4b3.png)

As I am not using the minitocs, a quick fix that worked for me was just add these to the preamble of my document:
```tex
\renewcommand{\mtocsection}[1]{}
\newcommand{\mtocsubsection}[1]{}
```
But a proper solution should be found for those that use the minitocs. 

### Additional Information

I have already written a comment on issue #101, but then I have realized that opening an issue was more appropriate.

**Comment by cgosorio** [comment]
I have identified what was causing the problem. In issue #101, the suggested definition for commands `\mtocsection` and `\mtocsubsection` was:
```tex
\newcommand{\mtocsection}[1]{
    \etoctoccontentsline{mtocsection}{\protect\numberline{\thesection}#1}
}
\newcommand{\mtocsubsection}[1]{
    \etoctoccontentsline{mtocsubsection}{\protect\numberline{\thesubsection}#1}
}
```

But in `kao.sty` these were incorporated as:
```tex
\newcommand{\mtocsection}[1]{
    \addcontentsline{toc}{mtocsection}{%
        \ifnum\value{secnumdepth}>0 \protect\numberline{\thesection}%
        \else \protect\nonumberline%
        \fi #1}%
}
\newcommand{\mtocsubsection}[1]{
    \addcontentsline{toc}{mtocsubsection}{%
        \ifnum\value{secnumdepth}>1 \protect\numberline{\thesubsection}%
        \else \protect\nonumberline%
        \fi #1}%
}
```
As suggested in etoc documentation, `\etoctoccontentsline` must be used instead of `\addcontentsline` to circumvent the patching for  automatic creation of bookmarks
done to `\addcontentsline` by the hyperref package. 

The problem with the wrong PDF hierarchy is solved if thee commands are defined as (although I do not know if the change will have any other impact in other parts of the document class):
```tex
\newcommand{\mtocsection}[1]{
    \etoctoccontentsline{mtocsection}{%
        \ifnum\value{secnumdepth}>0 \protect\numberline{\thesection}%
        \else \protect\nonumberline%
        \fi #1}%
}
\newcommand{\mtocsubsection}[1]{
    \etoctoccontentsline{mtocsubsection}{%
        \ifnum\value{secnumdepth}>1 \protect\numberline{\thesubsection}%
        \else \protect\nonumberline%
        \fi #1}%
}
```

I think with this the issue could be close, but I prefer the author of the package closes it after incorporating the changes to `kao.sty`.

**Comment by callegar** [comment]
Not working here. Getting
```
ERROR: Missing number, treated as zero.

--- TeX said ---
<to be read again> 
\Etoc@level 
l.217 \chapter{Blah blah}
```

**Comment by fmarotta** [comment]
Thank you very much, I have implemented the changes you suggested.
