### ISSUE TITLE
Formatting problem when there are sidenotes in section titles

### ISSUE THREAD

**Issue by cgosorio** [fmarotta/kaobook#156]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description

The sidenotes in section titles appear also in the minitoc, this has two consequences, first the sidenote is duplicated (it appears both realated to the title and to the minitoc), second the minitoc sidenote may overlap with another sidenote in main text, as it is shown in this image:

![image](https://user-images.githubusercontent.com/7659408/121773714-f06da480-cb7d-11eb-9523-6a5b53307b86.png)

The section titles causing the problem is:
```tex
\section[Boxes \& Environments]{Boxes \& Custom Environments
\sidenote[][*1.8]{Notice that in the table of contents and in the 
	header, the name of this section is \enquote{Boxes \& Environments}; 
	we achieved this with the optional argument of the \texttt{section} 
	command.}}
```
Where the optional argument with the titles without the sidenot is given. So the problem may be due to the fact that in the minitoc the optional argument is not used, but instead the mandatory argument of the section (with the sidenote) is used.

**Comment by cgosorio** [comment]
This problem seems related to the changes introduced in issue #101. One way to avoid the problem is to use the new optional argument:
```tex
\section[Boxes \& Environments]{Boxes \& Custom Environments
\sidenote[][*1.8]{Notice that in the table of contents and in the 
	header, the name of this section is \enquote{Boxes \& Environments}; 
	we achieved this with the optional argument of the \texttt{section} 
	command.}}[Boxes \& Environments]
```
Anyway, this is a bit cumbersome, when the new additional optional argument (for the minitoc) is not provided, I think the behaviour should be to use the first optional argument (for the toc) if provided. So, for example, for the case of the new section command, instead of the suggested:
```tex
\RenewDocumentCommand\section{s o m o}{%
    \IfBooleanTF{#1}{%
        \oldsection*{#3}
        \IfNoValueF{#2}{% if TOC arg is given create a TOC entry
            \addxcontentsline{toc}{section}[\thesection]{#2}%
        }%
    }{% no star given
        \IfNoValueTF{#2}{%
            \oldsection{#3}%
        }{% no TOC arg
            \oldsection[#2]{#3}%
        }%
        \IfNoValueTF{#4}{% optional label given, if not we do nothing
            \mtocsection{#3}%
        }{%
            \mtocsection{#4}%
        }%
    }%
}
```

This could be used:
```tex
\RenewDocumentCommand\section{s o m o}{%
    \IfBooleanTF{#1}{%
        \oldsection*{#3}
        \IfNoValueF{#2}{% if TOC arg is given create a TOC entry
            \addxcontentsline{toc}{section}[\thesection]{#2}%
        }%
    }{% no star given
        \IfNoValueTF{#2}{%
            \oldsection{#3}%
        }{% no TOC arg
            \oldsection[#2]{#3}%
        }%
        \IfNoValueTF{#4}{% optional label given, if not we do nothing
            % \mtocsection{#3}%
            \IfNoValueTF{#2}{% 
                \mtocsection{#3}% when no optional toc title, use main title
            }{% no TOC arg
                \mtocsection{#2}% when toc optional title is given, use it
            }%
        }{%
            \mtocsection{#4}%
        }%
    }%
}
```
Similarly, for the subsection command.

Still, the problem with the PDF hierarchy in #155 persists.

**Comment by fmarotta** [comment]
I incorporated the suggested changes. Thanks! For future reference, I don't dislike pull requests :}

**Comment by cgosorio** [comment]
Yes, sorry, next time I will prepare a PR. I have done this and other small corrections to the sources on the fly while preparing a document, and everything was a bit messy. This was the only substantial change I though could be urgent to incorporate. Now I need to meet the deadline to finish and send the document. But as soon as I have more time, I will prepare a proper PR with all those small changes.

Very nice book format, by the way, keep up your  good work.
