### ISSUE TITLE
Compilation - kaobook hangs when compiled

### ISSUE THREAD

**Issue by Krytic** [fmarotta/kaobook#157]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description

pdflatex hangs when it is compiled using `pdflatex -output-directory examples/documentation main.tex`. It works fine on Overleaf. I get the following log:

<details>
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)

 restricted \write18 enabled.

entering extended mode

(examples/documentation/main.tex

LaTeX2e <2021-06-01>

L3 programming layer <2021-06-01> (./kaobook.cls

Document Class: kaobook 2021/06/02 v0.9.7 kaobook

(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/scrbook.cls

Document Class: scrbook 2021/03/17 v3.33 KOMA-Script document class (book)

(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/scrkbase.sty

(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/scrbase.sty

(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/scrlfile.sty

(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/scrlfile-hook.sty

(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/scrlogo.sty)))

(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics/keyval.sty)))

(/usr/local/texlive/2021/texmf-dist/tex/latex/koma-script/tocbasic.sty)

</details>

I've checked #74 etc and my KOMA-Script is up to date (`cat-version: 3.33`).

### Minimal Working Example
The `documentation` example

**Expected behavior:** Compilation

**Actual behavior:** Not compilation

### Additional Information

The log above is shown as an image.

![Image of error message](https://i.imgur.com/rp0wVTN.png)

**Comment by yordiak** [comment]
I am also facing the ssame problem

**Comment by yordiak** [comment]
This problem is not related to kaobook. See [here](https://tex.stackexchange.com/questions/600701/why-doesnt-pdflatex-compile-my-project)

**Comment by yordiak** [comment]
The problem solved with the latest latex update (on Texlive 2021). Thus, this issue can be closed

**Comment by Krytic** [comment]
Correct -- for any others encountering this, run `tlmgr update --all` and the package will be updated.

**Comment by RemDelaporteMathurin** [comment]
> Correct -- for any others encountering this, run `tlmgr update --all` and the package will be updated.

Hi @Krytic , super this does seem to work locally. Though I'm trying to use GA to compile a Latex project using this class, and the build hangs because of this, do you know how to run this command within this Github Actions workflow (below) ?

Thanks!

```
name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile document.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: document.tex
```

**Comment by koppor** [comment]
Please update to the latest version. We changed from `master` to `edge` (and `latest`). `latest` is the latest released build, the `edge` is always the most recent version (built approx each 14 days). Thus, there will be most two weeks delay. No need to run `tlmgr update --all` in most of the cases.

See https://github.com/dante-ev/latex-action/blob/edge/CHANGELOG.md#changelog for details - and the updated `README.md` at https://github.com/dante-ev/latex-action#latex-action-.

Sorry for the name change. I thought, I should also follow the general movement away from `master` (see https://github.com/github/renaming#renaming-the-default-branch-from-master for details).
