### ISSUE TITLE
Use a format that differentiates sections and subsections in minitoc

### ISSUE THREAD

**Issue by cgosorio** [fmarotta/kaobook#158]
## Summary

I do not know if it has been a design decision, but in the minitoc both section and subsection appear with the same format, what I think it should not been the case. My humble opinion is that the subsection entries should not been in bold.

## Details

Changing this line in `kao.sty`:
```tex
        {\makebox[0pt][r]{\makebox[\margintocnumwidth][l]{\etocnumber}}\etocname\nobreak\leaders\hbox{\hbox to 1.5ex {\hss.\hss}}\hfill\rlap{\makebox[\margintocpagenumwidth][r]{\etocpage}}\par}%
        {\makebox[0pt][r]{\makebox[\margintocnumwidth][l]{\mdseries\etocnumber}}
```
by this other one (where the only change is to add the command \mdseries before the elements that show content in the toc entry):
```tex
{\mdseries\etocname}\nobreak\leaders\hbox{\hbox to 1.5ex {\hss.\hss}}\hfill\rlap{\makebox[\margintocpagenumwidth][r]{\mdseries\etocpage}}\par}%
```
Seems to be enough to achieve the suggested format. 

Probably it would be necessary to change also the command in the dry run used to get the sizes, but only with the change above the result seems satisfactory.

Also, I think in the showcase shown in the Appendix A could be more complete if it shows the minitoc too.

Finally, perhaps in the future specific koma fonts could be used for section and subsection in the minitoc different from the koma fonts for section and subsection in the text.

**Comment by fmarotta** [comment]
Would you also leave out the subsection number?

**Comment by fmarotta** [comment]
Assuming no, the following comment will address the issue :)

**Comment by cgosorio** [comment]
> Would you also leave out the subsection number?

No, that was my mistake, in my proposal of solution I forgot to paste the second line, sorry. I will correct it, in my comment.
