### ISSUE TITLE
Including an image in the main file

### ISSUE THREAD

**Issue by me7pako** [fmarotta/kaobook#159]
I apologize for not being an expert in LateX, but I have found a problem since I use kaobook format for my thesis. 
Btw, thanks a lot for the terrific work.

So my issue is as follows: 
I am trying to insert an image after the publishers' part (which for me is in the 5th page) but I keep getting the image on the first image.

Here is a snippet of the code:

%%%%
\titlehead{}
\subject{Written report of the project}
\title[Example and documentation of the kaobook class]{Title of the thesis\\}
\author[me]{me \\ \\Under the supervision of: \\Prof. Dr.-Ing.  \\M. Eng.}
\date{\today}
\begin{figure}
\centering
\includegraphics[width=7cm,page=5,keepaspectratio]{C:/Users/49157/Desktop/Studium/logo.png}
\end{figure}
\publishers{name of university}
%%%%

Thanks again guys for the terrific work.

**Comment by AlexanderZeilmann** [comment]
Can you post a minimal example that can be copy and pasted and runs without any errors? Otherwise, it is close to impossible to help you.

**Comment by fmarotta** [comment]
The `\begin{figure} - \end{figure}` in that position is wrong: it will not put an image in the place where you might expect. All the `\titlehead`, `\author`, `\date`, etc. commands only store their argument they it is 'rendered' by `\maketitle`. Thus, you could put the `\includegraphics` directly in argument of the `\publisher` command, like so:

```
\titlehead{}
\subject{Written report of the project}
\title[Example and documentation of the kaobook class]{Title of the thesis}
\author[me]{me Under the supervision of: Prof. Dr.-Ing. M. Eng.}
\date{\today}
%\begin{figure}
%\centering
%\includegraphics[width=7cm,page=5,keepaspectratio]{C:/Users/49157/Desktop/Studium/logo.png}
%\end{figure}
\publishers{name of university \includegraphics[width=7cm,page=5,keepaspectratio]{C:/Users/49157/Desktop/Studium/logo.png}}
```

**Comment by me7pako** [comment]
Thank you @fmarotta , that solved it to me.
Thanks again.
