### ISSUE TITLE
Activating the .sty file

### ISSUE THREAD

**Issue by pwgallagher** [fmarotta/kaobook#16]
I like this design a lot. I cloned the GIT but, because I rely mostly on TeXLive, it's been a long time since I had to integrate new .sty files. I had forgotten the details: I had to put the clone in a local 'texmf' directory (.../txmf/tex/latex/kaobook/) and then 'kpsewhich kao.sty' to verify LaTeX would find the files. Might possibly mention this the README.

**Comment by fmarotta** [comment]
Thank you for the suggestion, I will surely mention this in the RADME. However, this issue also reminds me that my .sty files are not polished yet, but there are some details that I would like to change. For instance, I want to make sure that the packages are independent from each other. Also, I have never integrated .sty files before, so I have to take some time to fully master the procedure. As soon as these little problems are gone, I will update the README and perhaps the documentation as well.

**Comment by fmarotta** [comment]
At last I have added the `instructions` directory to the repository, where I have put your advice. Thanks for contributing!
