### ISSUE TITLE
Reference rendering

### ISSUE THREAD

**Issue by dimitri-yatsenko** [fmarotta/kaobook#165]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description

I may be missing something obvious but when I follow instructions for local compile, my bibliography references remain unresolved. 

### Minimal Working Example
Simply compiling the documentation document locally following the instructurions.

**Expected behavior:**
![image](https://user-images.githubusercontent.com/1096169/128218766-d39db4da-ed5d-4080-848c-5e79ebd10527.png)

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/1096169/128218376-89cb80e6-dfb5-407a-b975-8b22cbea2ee7.png)

### Additional Information

[Any relevant additional information]

**Comment by enricostragiotti** [comment]
I've your very same problem..

**Comment by fmarotta** [comment]
Sorry to hear that. Are you running these commands from the root of the repository? They still work for me.
```
pdflatex -output-directory examples/documentation main.tex
biber -output-directory examples/documentation main
pdflatex -output-directory examples/documentation main.tex
pdflatex -output-directory examples/documentation main.tex
pdflatex -output-directory examples/documentation main.tex
```

**Comment by enricostragiotti** [comment]
I've identified the problem:
There is a conflict between the new command defined in kaorefs.sty (line 166) and the package mathtools.
![image](https://user-images.githubusercontent.com/44843509/128320370-fbc48bb9-692c-4a4d-ba3a-86f2a4b8ba25.png)

Once I've changed the new command name, all started to work correctly!

**Comment by dimitri-yatsenko** [comment]
hmm..  Still not getting `\sidecite` to work even when running on `pdflatex` three times. Fixing `refeq` did not help either. Is that really related? Mysterious.

**Comment by fmarotta** [comment]
@dimitri-yatsenko , could you please post the output you see when you run the `biber` command? Also, which LaTeX distribution are you using? TeXLive, MiKTeX, or something else? And which version? :)

**Comment by dimitri-yatsenko** [comment]
Thank you, @fmarotta. I am on MacOS.

## pdflatex version
```
% pdflatex -version
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)
kpathsea version 6.3.2
Copyright 2020 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.02
```

Output of the biber command:
```
% biber -output-directory examples/documentation main       

INFO - This is Biber 2.14
INFO - Logfile is 'examples/documentation/main.blg'
INFO - Reading 'examples/documentation/main.bcf'
INFO - Found 4 citekeys in bib section 0
INFO - Processing section 0
INFO - Globbing data source 'main.bib'
INFO - Globbed data source 'main.bib' to main.bib
INFO - Looking for bibtex format file 'main.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source 'examples/documentation/main.bib'
```

**Comment by dimitri-yatsenko** [comment]
ok. It worked today. I needed to I ran `pdflatex` four times after `bibex` rather than three.  I am closing the issue. Thank you for developing this awesome template!
