### ISSUE TITLE
enumitem inline option

### ISSUE THREAD

**Issue by ratmice** [fmarotta/kaobook#166]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description

[Description of the issue]
Must edit style to enable \usepackage[inline]{enumitem}

### Minimal Working Example
[You can use the following document to help you create a minimal working example.]
```
\documentclass{kaobook}
\usepackage[english]{babel}
\usepackage{blindtext}
\usepackage{kaobiblio}
\usepackage{kaotheorems}
\usepackage{kaorefs}
\usepackage[inline]{enumitem}

\begin{document}

\title{Bug Report}
\author{Author}
\date{\today}

\frontmatter

\KOMAoptions{twoside=semi}
\maketitle
\KOMAoptions{twoside=false}

\mainmatter
\setchapterstyle{kao}

\chapter{First Chapter}
\begin{enumerate*}
\item horizontal \item enumerate
\end{enumerate*}
\end{document}

```

**Expected behavior:**

**Actual behavior:**
Because kao.sty loads enumitem with no options, It isn't able to load it with the inline option.

changing `kao.sty` to use `\RequirePackage[inline]{enumitem}`, works 

If i understand correctly the inline option adds new environments like `enumerate*`,
rather than changing any existing package behavior of the typical environments.
Though there are some warnings in the enumitem documentation about floats

I haven't run across anything that didn't work with an edited kao.sty enabling the option,
I imagine that the warnings don't matter unless I put one in a float.

Is it worth considering enabling this option?

```
! LaTeX Error: Option clash for package enumitem.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.9

?
! Emergency stop.
 ...

l.9

The package enumitem has already been loaded with options:
  []
There has now been an attempt to load it with options
  [inline]
Adding the global options:
  ,inline
to your \documentclass declaration may fix this.
Try typing  <return>  to proceed.
```
### Additional Information

[Any relevant additional information]

**Comment by fmarotta** [comment]
Done, let me know how it goes!

**Comment by ratmice** [comment]
Works fine, both in the example above and actual document.  Thank you.
