### ISSUE TITLE
I am having a problem that left me pulling my hair

### ISSUE THREAD

**Issue by me7pako** [fmarotta/kaobook#167]
I am writing a thesis with kaobook but I am facing a problem.
Everything was going fine for more than 2 months. Now I tried to compile the main file and kept getting errors. After searching within the files I found that the \labfig and labch\ are causing the error so I had to comment them out for my file to compile. 
I fI do not comment them out I get this following error (this error was for when I tried to execute the compileall file):

! Undefined control sequence.
l.4 \labch
          {intro}
?

You notice the error happens on the 4th line of the first chapter. When I comment it out it gives error on the next \labch or \labfig (at least those are the two I know of).
So it sorta does not build the table of figures at the end. What can the problem be? I am using MikTex and I have installed it over and over and over. I also cloned the repo and replaced the old .sty files with the new ones I had.

Please help me.. I went so far with this report that I kept pulling my hair after I had this trouble and I need to finish my thesis report. Thanks in advance.

Update: I even tried to do this to the original main.tex file (I thought that I may have done something to the files I have) but in vain: I get the same error.

Update: it seems it happens with \reftab \refch \vrefpage as well.

Another update: when I replaced \labch with label[chapter:xxxx} it kinda worked. But I do not know what I need to do with the others since I found this mentioned literally in the PDF guide. Is it an .sty file that I need to put within the repository, because if yes then I did put the files in the styles folder as well as in the same folder where the main is. I also put the updated files in a folder that I added to MikTeX. Now I am out of ideas.

Another update: it seems to work on Overleaf while producing errors related to this exact syntax:

l.4 \labch
          {intro}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

**Comment by fmarotta** [comment]
Sorry to hear that! Do you have this line:
```
\usepackage{kaorefs}
```
in your main.tex? Because all the commands that give you errors are defined in the file 'kaorefs.sty' so my first guess would be that something is wrong with this file.
