### ISSUE TITLE
Margintoc bold sections not rendered correctly

### ISSUE THREAD

**Issue by enricostragiotti** [fmarotta/kaobook#168]
Hello Federico!
I'm using the kaobook class to write a PhD thesis and I really love the template!

While I was testing the `\margintoc` function, I noticed that unfortunately there's some inconsistency in the bold font: only the first consecutive sections are displayed in bold. I'm using the kaobook class with the option `secnumdepth` set to 2.
Here's an image with an MWE
![image](https://user-images.githubusercontent.com/44843509/131144497-d51290aa-dcc3-4392-a793-28aa75b79af8.png)

MWE
```
\setchapterpreamble[u]{\margintoc}
\chapter{Bibliography Review}\label{chap:bib-rev}
\section{Hi}
\section{Test}
\subsection{test}
\section{Hello} % This section is not bold
\subsection{Foo}
```

Thank you very much for your help!

Enrico

**Comment by hCarlFelix** [comment]
I also stumbled upon this error. I found that it is due to the \etocsetstyle{mtocsubsection} section in kao.sty. The culprit can be found on line 996 in kao.sty

```
993 \etocsetstyle{mtocsubsection}%
994 {\parindent 0pt \parskip 0pt \parfillskip 0pt \RaggedRight}%
995 {\leftskip \margintocnumwidth \rightskip \margintocpagenumwidth}%
996 {\makebox[0pt][r]{\makebox[\margintocnumwidth][l]{\mdseries\etocnumber}}\mdseries\etocname\nobreak\leaders\hbox{\hbox to 1.5ex {\hss.\hss}}\hfill\rlap{\makebox[\margintocpagenumwidth][r]{\mdseries\etocpage}}\par}%
997 {\parskip 2.5pt}%
```

In which the fontstyle is changed to mdseries. By grouping that section you can prevent it from overriding the rest of the toc. To accomplish this, you may change line 996 from
```
{\makebox[0pt][r]{\makebox[\margintocnumwidth][l]{\mdseries\etocnumber}}\mdseries\etocname\nobreak\leaders\hbox{\hbox to 1.5ex {\hss.\hss}}\hfill\rlap{\makebox[\margintocpagenumwidth][r]{\mdseries\etocpage}}\par}%
```
into
```
{\makebox[0pt][r]{\makebox[\margintocnumwidth][l]{\mdseries\etocnumber}}{\mdseries\etocname\nobreak\leaders\hbox{\hbox to 1.5ex {\hss.\hss}}\hfill\rlap{\makebox[\margintocpagenumwidth][r]{\mdseries\etocpage}}}\par}%
```

**Comment by enricostragiotti** [comment]
It works! Thank you very much for the answer!
I hope it's gonna be fixed on the main branch!

**Comment by fmarotta** [comment]
Hi, I've fixed it in the main branch. Thanks!
