### ISSUE TITLE
Feature Request: Adding Abstract Page

### ISSUE THREAD

**Issue by suhasbn** [fmarotta/kaobook#175]
Thanks for making this template. 
I wanted to request adding an Abstract page to the template if possible.

**Comment by fmarotta** [comment]
Sorry, I think this question pertains contents, not style, so I don't think any changes to the template are required. In the `kaobook` template, you can simply create an unnumbered chapter called "Abstract", and you can put it wherever you want (befeore the table of contents, after the table of contents, at the end of the document...). Then, you can change the style of that page as you wish using standard LaTeX. Looking at the kaobook documentation, the "Preface" chapter can be seen as an abstract. I would just rename that chapter from "Preface" to "Abstract". Let me know if you need further help with the customisation, or ask on tex.stackexchange.com :)
