### ISSUE TITLE
Incorrect spacing of margin figures in "List of Figures"

### ISSUE THREAD

**Issue by denniskb** [fmarotta/kaobook#178]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description

Normally, in the "List of Figures", figures are grouped by the chapter they appear in. Figures from the same chapter are close together while groups of figures from different chapters are spaced apart. Margin figures (`\begin{marginfigure}`) do not obey this spacing. See this [screenshot](https://ibb.co/4jY0GjT)--7.1 is a margin figure, while 7.2 is a standard figure.

**Comment by fmarotta** [comment]
Can you provide a minimal working example?
Also see #77

**Comment by denniskb** [comment]
I will try to post one later. For now I have narrowed the bug down to: If the *first* figure in a chapter is a marginfigure, it will be grouped with the preceeding chapter's figures inside the "List of Figures".

**Comment by denniskb** [comment]
"Minimal" working example: https://www.overleaf.com/read/dntfknjjxstm

**Comment by denniskb** [comment]
> Can you provide a minimal working example? Also see #77

Same issue

**Comment by fmarotta** [comment]
Let's discuss in #77, then
