### ISSUE TITLE
Prevent title page from printing

### ISSUE THREAD

**Issue by jacubero** [fmarotta/kaobook#183]
## Summary

Prevent title page from printing

## Details

I wonder if it is possible not to print the title page, and to start with the copyright page, for instance.  When I try to remove the \title{} command, I get the error:

! LaTeX Error: No \title given.

**Comment by fmarotta** [comment]
Hi, unfortunately it is not possible (or at least not easy). In fact, both the title page and the copyright page are printed out by the same command: `\maketitle`. Basically, first you use some commands like "\title{}", "\uppertitleback{}", etc. to define the contents, and then `\maketitle` arranges everything on the appropriate pages. If you don't want the title, I think the easiest thing to do is to omit the `\maketitle` command from your document, and then optionally create some special pages for the copyright, the quote, or what not. You can use standard LaTeX for that :) Please let me know if you need further help, or ask on tex.stackexchange.com.

**Comment by AlexanderZeilmann** [comment]
Additional comment:
The `\title` of the document does not only appear on the title page but also for example in the metadata. This is why you get the error if you do not define the `\title`.

I think the easiest way to solve your problem, is to create the document with a `\title` and a  title page and then delete all unwanted pages from the PDF using a PDF editor.

**Comment by fmarotta** [comment]
Good idea, using a PDF editor would be better :)

**Comment by jacubero** [comment]
Thank you for your answers. I tried using PDF editors some time ago, but they had a drawback (at least those I tried): They removed the pdf bookmarks. I will like to maintain the bookmarks. Do you know if it is possible to do it?

**Comment by fmarotta** [comment]
Right, removing a page probably messes up all the page numbers, so it's difficult to preserve bookmarks. I don't know any editor with this feature, sorry about that.

**Comment by AlexanderZeilmann** [comment]
[Master PDF Editor](https://code-industry.net/masterpdfeditor/) can delete the first page without destroying the bookmarks (at least in the two test documents I tried).

The current version of Master PDF Editor (Version 5) costs 70$, but you can still find installers for version 4 (which was free) all over the internet.
