### ISSUE TITLE
Adjustbox clashes with Kaobook?

### ISSUE THREAD

**Issue by DesKartes** [fmarotta/kaobook#186]
Hello,
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description

When using the adjustbox-package I see a strange behavior: The content of my minipage  is written in a larger font.

### Minimal Working Example
\documentclass{kaobook}

% Set the language
\usepackage[ngerman]{babel} % Load characters and hyphenation

% Load the bibliography package
\usepackage{styles/kaobiblio}
\addbibresource{main.bib} % Bibliography file

% Load mathematical packages for theorems and related environments. NOTE: choose only one between 'mdftheorems' and 'plaintheorems'.
\usepackage{styles/mdftheorems}
%\usepackage{styles/plaintheorems}

\usepackage[etex]{adjustbox}

\begin{document}

\setchapterstyle{kao}

\chapter{First Chapter}

1. \hfill \adjustbox{valign=t}{\begin{minipage}{0.3\linewidth}
    Test
\end{minipage}}%
\hfill
\adjustbox{valign=t}{\begin{minipage}[t]{0.6\linewidth}
Test2
\end{minipage}}

1. \hfill {\begin{minipage}{0.3\linewidth}
    Test
\end{minipage}}%
\hfill
{\begin{minipage}[t]{0.6\linewidth}
Test2
\end{minipage}}

\end{document}

The content of the minipage (numbers, tabular-part) are of different heights and should be aligned vertically and of course, font size should not alter. The package works fine in the tufte or book  class.
![grafik](https://user-images.githubusercontent.com/94788992/142763925-344a5db5-d526-433f-98f5-b2817e19cd7e.png)

### Additional Information

Minimal example: I can not delete the loading of bibliography and mdftheorems part, or the source would not compile on my pc. The original example file could not compile and the Wizzard of Vel told me, it was a bug and I should and did change:
 
add in kao.sty line 644: \let\Bbbk\relax

any hint would be appreciated
Ulrich

PS: I posted this question also on: https://latex.org/forum/viewtopic.php?f=59&t=34617&p=116821#p116821

**Comment by fmarotta** [comment]
Thanks for reaching out. Indeed, it seems that kaobook does weird things with the adjustbox package. The reason is that, in `kao.sty`, you can find the line `\setkeys{Gin}{width=\linewidth,totalheight=\textheight,keepaspectratio}`. Adjustbox also uses the Gin key, so its boxes are affected by this `\setkeys{Gin}` command. An easy fix is to add this line in the preamble of your main.tex, either before or after `\usepackage{adjustbox}`:

```
\setkeys{Gin}{keepaspectratio=!,width=!,height=!}
```

I am in the process of removing unnecessary things from the package and this line may go away in a future release.

**Comment by DesKartes** [comment]
thx :-)
