### ISSUE TITLE
wrapfigure not properly placed in kaobook-class? 

### ISSUE THREAD

**Issue by DesKartes** [fmarotta/kaobook#187]
Hello,

### Description

It seems kaobook and wrapfig don't like each other. The text inside the wrapfigure environment is not properly placed. It seems it is to far left (\width ?). 

### Minimal Working Example
\documentclass{kaobook}

% Set the language
\usepackage[ngerman]{babel} % Load characters and hyphenation

% Load the bibliography package
\usepackage{styles/kaobiblio}
\addbibresource{main.bib} % Bibliography file

% Load mathematical packages for theorems and related environments. NOTE: choose only one between 'mdftheorems' and 'plaintheorems'.
\usepackage{styles/mdftheorems}
%\usepackage{styles/plaintheorems}

\usepackage{wrapfig}

\usepackage{blindtext}

\begin{document}

\setchapterstyle{kao}

\chapter{First Chapter}

\begin{wrapfigure}[]{r}[0cm]{0pt}
\begin{tabular}[t]{cccc}
\multicolumn{4}{c}{Irgendein Text}\\
\hline
West & Nord & Ost & Süd \\
 \hline
  && Pass & Eintrag\\
 Eintrag  & Eintrag & - ? - & \dots      \\
   \hline \\
  \end{tabular}
\end{wrapfigure}
\blindtext

\begin{wrapfigure}[]{l}[0cm]{0pt}
\begin{tabular}[t]{cccc}
\multicolumn{4}{c}{Irgendein Text}\\
\hline
West & Nord & Ost & Süd \\
 \hline
  && Pass & Eintrag\\
 Eintrag  & Eintrag & - ? - & \dots      \\
   \hline \\
  \end{tabular}
\end{wrapfigure}
\blindtext

\end{document}

I need a possibility to place information that takes some space from the text- and the margin-area. Ideally, if the info is too wide for the margin the necessary area from the textbody.

### Additional Information

Minimal example: I can not delete the loading of bibliography and mdftheorems part, or the source would not compile on my pc. The original example file could not compile and the Wizzard of Vel told me, it was a bug and I should and did change:

add in kao.sty line 644: \let\Bbbk\relax

any hint would be appreciated
Ulrich

**Comment by fmarotta** [comment]
Hi, thanks again. The problem stems from using the package `floatrow` and `wrapfig` at the same time. The "wrapfigure" environment is a subtype of the "figure" environment, so when `floatrow` changes the figure environment, it automatically changes wrapfigures as well. The solution is add these two lines *after* loading `floatrow`:
```
\RawFloats[figure][wrapfloat]
\RawFloats[table][wrapfloat]
```

**Comment by DesKartes** [comment]
thx :-)
