### ISSUE TITLE
Using minted with kaobook

### ISSUE THREAD

**Issue by acotorruelo** [fmarotta/kaobook#189]
Hi,

I'm trying to substitute the listing package with minted in the kaobook class, but so far I haven't made much progress. I've searched online, and all I could find was a post from 8 months ago that suggested to load scrhacks  with \AtEndPreamble, but it doesn't work for me, I'm assuming it's because the class has been updated since then. Any help would be greatly appreciated, thanks in advance.

**Comment by fmarotta** [comment]
Hi, thanks for reaching out. the scrhack package is loaded internally by the class, so the only way to fix the problem is to change the class files. In the next commit the issue should be solved. Can you please try again to use minted after downloading the latest version?
