### ISSUE TITLE
Renumbering of sidenotes within each chapter

### ISSUE THREAD

**Issue by HosseinJorjani** [fmarotta/kaobook#19]
Dear Federico,

I would like to have the sidenotes starting from 1 in each chapter.
I have uncommented the following line from the file "style.sty":

\counterwithin*{sidenote}{chapter} % Uncomment to reset the sidenote counter at each chapter

When I compile (typeset) the files through Texworks (Miktex 2.9), there are
two problems: 
First: 
The above command does not make the re-numbering within each chapter;

Second: 
Sidenotes for chapter 1 are numbered 1 and 2;
Sidenotes for chapter 2 are numbered 5 and 6;
Sidenotes for chapter 3 are has only 9 and 10.

When I compile the files using the commands in the file "compileall.sh":
((Please notice that somehow I cannot execute the file "compileall.sh" on its own. So, I run the commands line by line)):

After running the following command:
pdflatex -interaction=nonstopmode main
I get the following results:

Sidenotes for chapter 1 are numbered 1 and 2, but in the middle of page;
Sidenotes for chapter 2 is shown only for the second sidenote, numbered as 2, but 
          half of the sidenote is visible in the margin;
Sidenotes for chapter is shown only for the second sidenote, numbered as 2, but 
          half of the sidenote is visible in the margin;
		  
Then running the following commands:
makeindex main.nlo -s nomencl.ist -o main.nls
makeindex main
biber main
pdflatex main
makeglossaries main
I (obviously) see no change.

Finnaly, after running the final command
pdflatex main
Everything goes back to the wrong re-numbering, i.e.

Sidenotes for chapter 1 are numbered 1 and 2;
Sidenotes for chapter 2 are numbered 5 and 6;
Sidenotes for chapter 3 are has only 9 and 10.

Is this a bug, or do I do something wrong?
Regards,
Hossein Jorjani

**Comment by fmarotta** [comment]
Dear Hossein,

Thank you for the detailed report. I suspect that this is a bug, and that it will be particularly nasty to fix. While I'm on it, let me at least tell you something about the other (minor) problems you mentioned.

The first thing that intrigued me is the impossibility to execute compileall.sh. Could you please tell me how you are running the script? I guess that the problem may be the lack of the permission of execution. If that is the case, running "chmod u+x compileall.sh" from the terminal should fix it.

Secondly, it is almost always necessary to compile the document more than once before the floating elements (such as sidenotes) are positioned correctly, so if you see only half of the sidenotes, try compiling again. Up to four compilations may be necessary.

Regards,
Federico

**Comment by fmarotta** [comment]
Dear Hossein,

I updated the kaobook class so as to use the `sidenotes` package instead of `snotez`. Now the bug you reported should be fixed. Indeed, the sidenote counter can be reset at every chapter using
`\counterwithin*{sidenote}{chapter}` (which now is the default), and it can be kept going for the whole document with `\counterwithout{sidenote}{chapter}`.

A possible drawback is that the syntax of the `\sidenote` command has changed: now the offset is the second optional argument, so you should have, e.g., `\sidenote[][*-1]{Text of the sidenote.}.`

Please let me know if you are still experiencing the problem with the new version.

Kind regards,
Federico

**Comment by HosseinJorjani** [comment]
Dear Federico,

Excellent, and thank you.

I did not download/clone anything from the repository today, because based on a message from GitHub from 2019-12-20 (see also my message to you on the same day), I had the renumbering fixed. 

Again, thank you.

Regards,
Hossein
