### ISSUE TITLE
template won't compile locally with Miktex/texstudio distribution on MS W10

### ISSUE THREAD

**Issue by ronanlefort** [fmarotta/kaobook#193]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description

I get a "Missing $ inserted. \chapter{First Chapter}" when I try to compile any kaobook example locally on my computer. The examples work online with overleaf, and I only have trouble with the kaobook template (all other book examples dowloaded from the "[Latex templates](http://www.latextemplates.com/)" web site work on first attempt.

See below a screen copy

Any idea ? 

![Capture](https://user-images.githubusercontent.com/95969006/145678793-89eba69f-2300-45fc-9ed8-49eaba2b76d1.PNG)

**Comment by jhsh** [comment]
I experience the same problem, with both the documentation files, and my own

**Comment by jhsh** [comment]
Compiling the main Kaobook documentation with MikTeX/TeXworks under Window 10 give the following errors:

With pdfLaTex and XeLaTeX:
chapter 1.
! Missing $ inserted.
<inserted text> 
                $
l.2 \chapter{Introduction}

With LuaLaTeX:
chapter 1.
! Improper \spacefactor.
<recently read> \spacefactor 
             
l.2 \chapter{Introduction}

**Comment by jhsh** [comment]
I reverted back to Kaobook 0.9.7, and the problem persists. I therefore doubt that it is a Kaobook problem.

**Comment by ronanlefort** [comment]
I found a solution : installed Tex Live 2021 instead of MikTex. 

Compiling with XeLatex instead of PdfLatex then works.

No idea why ;)

**Comment by AlexanderZeilmann** [comment]
Does the problem only occur with `kaobook` or does it also exist with normal `koma-script` documents?
That is a nice check to see whether there is a bug in `kaobook` or somewhere else.

**Comment by jhsh** [comment]
The current koma-script works fine:

\documentclass{scrartcl}
\begin{document}
test
\end{document}

**Comment by AlexanderZeilmann** [comment]
Thank you for your investigations @jhsh! My current understanding is the following:

The nexpx-font package slightly changed the definition of the `theoremfont` parameter.
This means, if we now want to use `theoremfont` like we did
```latex
\RequirePackage[scaled=.97,helvratio=.93,p,theoremfont]{newpxtext}
```
we have to include the package `amsthm` before `nexpxtext`.
As an aside, the problem also appears in other document classes, if `amsthm` is not loaded before `nexpxtext`.


There are several ways of fixing the bug:

## 1. Drop `theoremfont`
In `kao.sty` replace
```latex
\RequirePackage[scaled=.97,helvratio=.93,p,theoremfont]{newpxtext}
```
by
```latex
\RequirePackage[scaled=.97,helvratio=.93,p]{newpxtext}
```
This fixes the error, however, we loss the `theoremfont` functionality.

## 2. Load `amsthm` before the font
Currently the situation is as follows:
```latex
\documentclass{kaobook}      % <-- newpx is loaded here
\usepackage[english]{babel}
\usepackage{blindtext}
\usepackage{kaobiblio}
\usepackage{kaotheorems}     % <-- amsthm is loaded here
\usepackage{kaorefs}
```
So `amsthm` is loaded after `nexpx`, which is a problem for `newpx`.
Loading `amsthm` in `kao.sty` before `newpx` fixes this problem, however, for people that do not want to use `kaotheorems` this might generate problems.

## 3. A slightly bigger rewrite
We could modify the template in the following way:
```latex
\documentclass[kaobiblio, kaotheorems, kaorefs]{kaobook}
\usepackage[english]{babel}
\usepackage{blindtext}
```
So the user specifies which `kao`-packages to load as documentclass-options.
In this way, we know whether the user wants to use `kaotheorem` already in `kao.sty` and we can load `amsthm` before `nexpx`.

---

**As a quick fix I would go with 1., but convert to 3. in the future.**

**Comment by jhsh** [comment]
Thanks @AlexanderZeilmann! I re-commented l.404 in nexpxtext.sty and implemented your solution 1, which of course works as advertised. However, the more serious original problem flagged by @ronanlefort and myself still remains unsolved.

**Comment by ronanlefort** [comment]
Thank you guys @AlexanderZeilmann & @jhsh for the discussion. We are a great step forward to the solution. Kaobook is such a nice class that it is really worth to dig further. I also noticed a conflict with the tikz package (and encoding math fonts) but I will keep this for a further issue when I identify more precisely the origin of the bug (which appears with Xelatex and not with Lualatex).

**Comment by AlexanderZeilmann** [comment]
@ronanlefort is the `"Missing $ inserted. \chapter{First Chapter}"`-bug fixed for you?

Sadly I can not reproduce this bug, so it is a little hard for me to debug this.

**Comment by jhsh** [comment]
No, the bug is still there. What is your setup (OS, tex distro)? From any differences we may be able to zoom in to the problem

**Comment by jhsh** [comment]
Could you please revert this issue to open?

**Comment by ronanlefort** [comment]
Indeed, I noticed that this error is the one left when you compile a second time with pdflatex. At first run, you get the "\theoremstyle" bug.

**Comment by AlexanderZeilmann** [comment]
> What is your setup (OS, tex distro)? From any differences we may be able to zoom in to the problem

Mac OS 10.15.4
TeXLive-2021-Basic
all package updates installed via the Tex Live Utility
`pdfTeX 3.141592653-2.6-1.40.23 (TeX Live 2022/dev)`
`XeTeX 3.141592653-2.6-0.999993 (TeX Live 2021)`
`LuaHBTeX, Version 1.13.2 (TeX Live 2021)`

**Comment by DesKartes** [comment]
I have no idea at all, but this is a hint I got, when I could not compile the main.file
---------------
Anyways, to fix the problem in the latest version of the template from my website, go to kao.sty and add this on line 644:

\let\Bbbk\relax

This is what lines 642-645 should look like afterwards:

\RequirePackage[scaled=.97,helvratio=.93,p,theoremfont]{newpxtext} % Serif palatino font

\RequirePackage[vvarbb,smallerops,bigdelims]{newpxmath} % Math palatino font

\let\Bbbk\relax % This is a hack to stop the newpxmath and amssymb packages both defining this command and leading to a compilation error 

\RequirePackage[scaled=.85]{beramono} % Monospace font
--------------------

**Comment by jhsh** [comment]
Thanks @DesKartes, but this does not solve the problem. I am not sure which version of kao.sty you refer to, but these lines occur at 1077-1079 in the current version.

**Comment by jhsh** [comment]
I have now also installed TeXLive under Windows 10 and can confirm that the kaobook documentation files and my own files compile without error with pdfLaTeX, XeLaTeX, and LuaLaTeX. So the problem must orginate with some file in MikTeX, and not with kaobook. We'll just have to wait until the bug is recognised and found by some MikTeX guru.

**Comment by jhsh** [comment]
The newpx and microtype MikTeX packages have just been updated, and with these updates both of the ""Missing $ inserted." and the 

! Undefined control sequence.
l.561 \theoremstyle
{plain}

errors do not occur anymore. Note that it is unnecessary to modify kaobook.sty as suggested by @AlexanderZeilmann.

@ronanlefort could you please check that you have the same experience? If so, then this issue can be safely closed.

**Comment by jhsh** [comment]
I apologise, but my previous comment was only partly correct. I discovered that after installing TeXlive its binaries were in the path before the mikTeX binaries. Once I corrected this the 
! Undefined control sequence.
l.561 \theoremstyle
{plain}
error came back, but fortunately the more problematic "Missing $ inserted." did not occur anymore.

**Comment by ronanlefort** [comment]
Hi @jhsh, @DesKartes, @AlexanderZeilmann 
I installed back the updated version of Miktex : that's OK now, provided you swith to p option in the call to the nexpxtext pacakage in kao.sty
Thank you guys
Have fun with this second to none kaobook class !
