### ISSUE TITLE
Page numbers for kaohandt

### ISSUE THREAD

**Issue by BenzoX** [fmarotta/kaobook#198]
Hello!
Page numbers are disabled by default in kaohandt (see, e.g., the machine learning project example and the minimal report example). I guess this is a feature, but I am wondering what is the cleanest way to turn them back on, if there is one?
Thanks!

**Comment by AlexanderZeilmann** [comment]
Add `\pagestyle{pagenum.scrheadings}` to your document or `\pagestyle{centeredpagenum.scrheadings}` if you want to have the page number centered. Note that it is a feature that the first page does not have a page number.

@fmarotta maybe the default page style for kaohandt should not be `plain`.
