### ISSUE TITLE
sidecite horizontal alignment

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fmarotta/kaobook#220]
### Description
Hi @fmarotta 

I'm encountering this issue with `sidecite` where long citations get misaligned (see below).
Is this a bug or am I doing something wrong?

Thanks!

### Minimal Working Example

```latex
\documentclass{kaobook}
\usepackage[english]{babel}
\usepackage{blindtext}
\usepackage{kaobiblio}
\usepackage{kaotheorems}
\usepackage{kaorefs}

\addbibresource{mybib.bib} % Bibliography file


\RenewDocumentCommand{\formatmargincitation}{m}{
	\parencite{#1} \citeauthor*{#1} (\citeyear{#1})\\
}

\begin{document}


\title{Bug Report}
\author{Author}
\date{\today}

\frontmatter
\maketitle
\mainmatter
\setchapterstyle{kao}

\chapter{First Chapter}
\blindtext
\sidecite{short}
\sidecite{long}

\end{document}
```

mybib.bib
```bib
@article{short,
	title = {Title1},
	journal = {Journal of Nuclear Materials},
	author = {Shortname},
	year = {2015},
}

@article{long,
	title = {Title2},
	journal = {Journal of Nuclear Materials},
	author = {VEEEERYLONGAUTHORNAME},
	year = {2015},
}
```

**Expected behavior:**
Alignment of the two citations

**Actual behavior:**
![image](https://user-images.githubusercontent.com/40028739/158641794-54fca310-d594-45d3-81d1-30e6d3912801.png)

**Comment by RemDelaporteMathurin** [comment]
@fmarotta maybe there's a flag in sidecite that forces the alignment to the left?

**Comment by pi8027** [comment]
@RemDelaporteMathurin Hi, does this fix the issue?
```latex
\RenewDocumentCommand{\formatmargincitation}{m}{%
	\parencite{#1} \citeauthor*{#1} (\citeyear{#1})%
}
```

**Comment by RemDelaporteMathurin** [comment]
Hi @pi8027 it does fix it! and it's well aligned now.
![image](https://user-images.githubusercontent.com/40028739/162289978-8e760ad7-23da-46ca-9c72-c0bb355087aa.png)
However there still is some were spacing in the name... any idea?

**Comment by pi8027** [comment]
@RemDelaporteMathurin If you just want to put a space of the same width after every [n], I would suggest:
```latex
\RenewDocumentCommand{\formatmargincitation}{m}{%
	\parencite{#1}\;\citeauthor*{#1} (\citeyear{#1})%
}
```
Here, `\;` has a fixed width of 5 mu. You may also replace it with `\hspace`.

**Comment by RemDelaporteMathurin** [comment]
@pi8027 Thanks! it fixed the space after [n]
![image](https://user-images.githubusercontent.com/40028739/162487318-fc5618a9-7e86-4a3b-96b6-34063a73068b.png)
is there a way to deactivate the text justification? Like on this screenshot the space between "Hammon" and "et" is really big!

**Comment by fmarotta** [comment]
Hi, perhaps this?
```
\RenewDocumentCommand{\formatmargincitation}{m}{%
	{\RaggedRight\parencite{#1}\;\citeauthor*{#1} (\citeyear{#1})}%
}
```
