### ISSUE TITLE
Feature Request: Make a xelatex/lualatex version

### ISSUE THREAD

**Issue by yordiak** [fmarotta/kaobook#23]
It could be nice to convert this template to a version that it is compatible with xelatex/lualatex engines. This could be really useful for multilingual books/theses/etc

**Comment by fmarotta** [comment]
Yeah, I like the idea :)
I'll start working on it, unless you already had something in mind; if so, please feel free to make a PR.

**Comment by yordiak** [comment]
I would like to contribute, however I am not familiar with tex/latex programming and github. Definitely, I can post some ideas and its up to if you if these are applicable or not

**Comment by fmarotta** [comment]
Sure, that would be nice!

**Comment by yordiak** [comment]
I am experiencing issues on running the class. Firstly, I comment every font/enconding command . Second in the preamble I use

```
\usepackage{fontspec}
\usepackage{uicode-math}

\setmainfont{STX 2 Text}
\setmathfont{STIX 2 Math}

\usepackage{polyglossia}
\setmainlanguage{greek}
\setotherlanguage{english}
```
However, I encounter problems with your kaocounter definition.

**Comment by yordiak** [comment]
I tried to compile your example "main_with_bibtex". 

In the preamble of the main document I replaced `babel` with `polyglossia` and also, I loaded the `stix2` font(because it supports greek characters).

The problem is that `kaobook` declares too many symbol fonts. Therefore, you comment some of packages that already define some math fonts in your class and/or in styles.

Therefore, I would propose the following. To create 2 tex files that contain only packages related to fonts. For instance, `lua_font.tex` and `pdf_font.tex`. Depending on your engine the respective `.tex` file will be loaded.

**Comment by fmarotta** [comment]
Thanks for your suggestions. I have made some modifications that should allow a painless usage of XeLaTeX or LuaLaTeX. In particular, I have added a "main_with_xelatex" file in the examples/documentation directory. I have also added some internal switches that turn on or off different options according to the compiling engine. The idea is that users who want to use xelatex or lualatex should refer to main_with_xelatex.tex, while the others should refer to main.tex, but the differences between the two files are minimal. 

With the following lines in the preamble of the main_with_xelatex.tex file,

```
\usepackage{polyglossia}
\setdefaultlanguage{english}
\setotherlanguage{greek}
\usepackage[english=british]{csquotes}
\setromanfont{STIX2Text-Regular.otf}
```

I was able to compile a healthy pdf with some parts in Greek. I was unable to reproduce the too-many-fonts problem, though. Please let me know if this update suits your needs.

**Comment by yordiak** [comment]
Thank you very much for your effort in this awesome class. 
However, I am experiencing the following error

> ! Undefined control sequence.
> <argument> ,\bbl@loaded 
>              ,
> l.78 \IfStringInList{english}{\bbl@loaded}
>                                         {
> ?

**Comment by fmarotta** [comment]
Try loading the polyglossia package before the kaobiblio package.

**Comment by yordiak** [comment]
I did this and the error persists. I managed to solve it by loading `biblatex` instead of your custom file.

Now my files runs without errors. However, I am not able to produce greek characters. I tried to define greekfontfamily, but it didn't solve the problem.

In my `.tex` files I also load `unicode-math`. I know that it creates a lot of problems, but for me it is an essential package (it allows me to change math font, and produces grek characters). 

However, when I loaded it in `kaobok` I count for declares too many symbol fonts. 

If you are interested in, I can send you an e-mail with my current set up, where greek characters work just fine.

**Comment by fmarotta** [comment]
OK

**Comment by yordiak** [comment]
awesome work. 

After the last update I was able to compile my document and to produce greek characters. Two things must be noted:
(1) For some reason, when I try to compile your example at the documentation folder I get an error : "babel error: Italian language is dot defined". The problem is solved by setting `\setotherlanguage{italian}` in the preamble.

(2) I cannot set greek as `\setmainlanguage`. `polyglossia` rejects `\newfontfamily\greekfont` definition. I guess this problem is related to `koma-script` class and not to `kaobook` itself.

So, I am closing this issue since apart from these 2 issues everything else is working as expected
