### ISSUE TITLE
Change the layout to a more screen appropriate format 

### ISSUE THREAD

**Issue by tobiasdossinger** [fmarotta/kaobook#242]
## Summary
Easy change of the view from portrait to landscape mode - more user-friendly when reading document on mobile device (laptops, tablets)

## Details
Is there a way to change the view from portrait to landscape mode, so my peers can read the document on a mobile device? In times, where scientific documents often get read on devices which have an aspect ratio of 16:9, it would be neat to hand the document in a more matching format than A4.

## Additional context
In the last two years, the request to hand in work in a matching format for scientific documents (landscape, or similar 16:9) increased massively at my university. My professors tend to read the documents on a laptop screen anyway.

If there is already an option to format the kaobook into a more screen related aspect ratio, I would appreciate getting an answer on this topic.

Sincerely,
Tobias Dossinger

**Comment by fmarotta** [comment]
There is an option: `a4paperlandscape`. See also #85. It'd be nice to have an option for 16:9, too, so I'll probably add it later. If I'm too slow and you want to give it a try before me, it should be as easy as adding one line after [this one](https://github.com/fmarotta/kaobook/blob/9719989592006711f53809f73c8c51abe9fb3092/kao.sty#L132), one just needs to figure out the appropriate ratios with the a4 dimensions.

**Comment by fmarotta** [comment]
I've added (and documented) an `169paperlandscape` option. Feel free to reopen the issue if something doesn't work or you need something else.

**Comment by tobiasdossinger** [comment]
After I opened this issue last week, I found the option: `a4paperlandscape`, but forgot to modify the issue. Thanks for hint about the option.
I was just about to start to implement the 16:9 aspect-ratio, then I saw that you already did it. 🥇 I'll keep you posted, if some notable bug occurs.

Thanks for the fast reply and implementation.
