### ISSUE TITLE
Help with formatting

### ISSUE THREAD

**Issue by rajevv** [fmarotta/kaobook#243]
Hi, thanks for this nice resource! I am using this template to write my thesis, and I would like to have the 1.5 column aligned to only one side (left) for all the pages. Currently, it switches from left to right alternatively? Can you please tell me how to make that happen? Thanks in advance!

**Comment by rajevv** [comment]
Figured it out.

**Comment by me7pako** [comment]
Would you mind sharing how you solved it for the others to learn from your experience?

**Comment by rajevv** [comment]
> Would you mind sharing how you solved it for the others to learn from your experience?

There is an option twoside in the main.tex. Set it to False.
