### ISSUE TITLE
Cannot use the empheq package

### ISSUE THREAD

**Issue by me7pako** [fmarotta/kaobook#247]
### Minimal Working Example

```latex
\documentclass{kaobook}
\usepackage[english]{babel}
\usepackage{blindtext}
\usepackage{kaobiblio}
\usepackage{kaotheorems}
\usepackage{kaorefs}
\usepackage{empheq}
\begin{document}

\title{Bug Report}
\author{Author}
\date{\today}

\frontmatter
\maketitle
\mainmatter
\setchapterstyle{kao}

\chapter{First Chapter}
\blindtext

\end{document}
```

**Expected behavior:**
<boxed multiline equations>

**Actual behavior:**
<a bug report : ! LaTeX Error: Command \refeq already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.166 ...hyperref[eq:#1]\eqname\xspace\ref{eq:#1}}
                                                  
? >

** Additional Information
I believe the issue is with the package kaorefs since in the errors box I get a link to kaorefs.sty

![image](https://user-images.githubusercontent.com/53613644/185672435-6c7e662a-c9f0-4ce3-b33e-37c5a3426aa6.png)

**Comment by fmarotta** [comment]
Hmm, I'd try to load kaorefs after empheq, and relax \refeq in between. In other words, I'd try to load the packages like so:
```
\usepackage{empheq}
\let\refeq\relax
\usepackage{kaorefs}
```
but let me know if it doesn't work.
