### ISSUE TITLE
Formatting issue: Uneven vertical spacing between paragraphs

### ISSUE THREAD

**Issue by tekrajchhetri** [fmarotta/kaobook#252]
Hi, 
@fmarotta  Thanks for the nice resources. I am currently using it for my work. However, when I don't have enough text in a chapter, there's an uneven vertical spacing between paragraphs (see image below). How do I make it evenly spaced even when there's not enough text? Thanks.   
![Screenshot 2022-09-05 at 11 02 51](https://user-images.githubusercontent.com/52251022/188415156-4af5cc6a-5603-44e8-9715-7ea5649aab5a.png)

Version: Version 1.3 (December 9, 2021)

**Comment by me7pako** [comment]
Can you put a solution to your problem?

**Comment by tekrajchhetri** [comment]
@me7pako  I adjusted the content and everything was fine. Other than that in the few cases, I used the _vspacing_.  Also, I have made few other adjustments in the template, which I will share after completing my thesis writeup.
