### ISSUE TITLE
Copyright page disappears

### ISSUE THREAD

**Issue by 0synonym** [fmarotta/kaobook#285]
The copyright page disappears when I set 
```
twoside=false
```
or
```
oneside=true
```
Copyright page section is not commented out. If I undo the setting, the copyright page appears again.
 I'm not sure if this is intentional. I would like to use a copyright page with an oneside layout.
I am using the last version 0.9.7.

**Comment by fmarotta** [comment]
Yes, this is a feature of KOMA-script. That page is created by `\maketitle` and technically it's meant to be the page on the back of the title, but still on the same "leaf". So it exists only in twoside mode. The easiest would be to typeset it manually after `\maketitle` with
```
\begin{titlepage}
bla bla bla copyright
\end{titlepage}
```

**Comment by 0synonym** [comment]
Hello Federico,
thanks for the clarification.
I had manually inserted copyright info after `\maketitle `similar to your suggestion.
