### ISSUE TITLE
Failed compilation on Mac

### ISSUE THREAD

**Issue by ErikPillon** [fmarotta/kaobook#30]
While trying to compile on a Mac the following message appears 

```
! LaTeX Error: Command \counterwithout already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.42 ...thout}{\@ifstar{\c@t@soutstar}{\c@t@sout}}
                                                  
?
```

The problem doesn't appear on a Linux based Operating System.

**Comment by TheoWinterhalter** [comment]
I think it's probably not related to your OS but rather on the fact that you have different installations of your packages or something like this on your two systems.
I can build kaobook projects just fine on my mac.

**Comment by ErikPillon** [comment]
> I think it's probably not related to your OS but rather on the fact that you have different installations of your packages or something like this on your two systems.
> I can build kaobook projects just fine on my mac.

Many thanks! I'll try to debug on my own and I'll close the issue.

**Comment by ErikPillon** [comment]
@TheoWinterhalter Indeed I updated my version of TeX Live and everything worked like a charm. Many thanks for the feedback.
