### ISSUE TITLE
Wrong output of minidocument

### ISSUE THREAD

**Issue by TheoWinterhalter** [fmarotta/kaobook#31]
I'm trying to use the [minidocument] package in my document to do a sort of "how to read" section.
However it doesn't render as hoped.
![Capture d’écran 2020-04-29 à 14 38 58](https://user-images.githubusercontent.com/5960860/80596757-2a85f080-8a27-11ea-92ee-d2cde0d0231a.png)
As you can see the lines and margin are misplaced.

I produce it using this
```latex
\begin{minidocument}
  \setchapterstyle{kao}
  \chapter{Dummy chapter}

  \blindtext~\sidecite{something}

  \marginnote[1cm]{\blindtext}
  \marginnote[4cm]{\blindtext}
  \marginnote[10cm]{\blindtext}
  \Blindtext
\end{minidocument}

\begin{figure}[hb]
  \lastminidocument
\end{figure}
```

I have
```tex
\usepackage{minidocument}
\def\minidocumentscale{0.25}
\usepackage{blindtext}
```
before the `\begin{document}`.

**Comment by fmarotta** [comment]
Sorry for the late reply.
I suspect it's a geometry problem... My best try was adding some code inside the minidocument environment (it enlarges the marginsep, without affecting the style of the chapter title). Note that `\setchapterstyle` should not be included anymore.

```
\begin{minidocument}
  \DeclareDocumentCommand{\chapterstylekao}{}{%
    \renewcommand*{\chapterformat}{%
        \mbox{\chapappifchapterprefix{\nobreakspace}\scalebox{2.85}{\thechapter\autodot}}%
    }   
    \renewcommand\chapterlinesformat[3]{%
        \vspace*{-4.5cm}%
        \makebox[\textwidth+8.2mm+\marginparwidth]{%
            \parbox[b]{\textwidth}{\flushright{##3}}%
            \makebox[8.2mm][c]{\rule[-.2cm]{1pt}{5.7cm}}%
            \parbox[b]{\marginparwidth}{##2}%
        }
    }   

    \RedeclareSectionCommand[beforeskip=0cm,afterskip=1cm]{chapter}
    \setlength{\mtocshift}{0mm}
  }
  \chapterstylekao
  \newgeometry{
    top=27.4mm,
	bottom=27.4mm,
	inner=24.8mm,
	textwidth=107mm,
	marginparsep=32mm,
	marginparwidth=49.4mm,
	includemp
  }%

  \chapter{Dummy chapter}
  \blindtext~\sidecite{something}
  \marginnote[1cm]{\blindtext}
  \marginnote[4cm]{\blindtext}
  \marginnote[10cm]{\blindtext}
  \Blindtext
\end{minidocument}
```

**Comment by TheoWinterhalter** [comment]
![Capture d’écran 2020-05-15 à 09 26 01](https://user-images.githubusercontent.com/5960860/82023155-192b1e00-968e-11ea-851b-46d13240f63b.png)
This is indeed much better! Thanks.
But there are still slight problems with this. It also messes up with the layout of the chapter it's in.

I won't be using minidocument anymore I think.
Thanks a lot.
