### ISSUE TITLE
Marginfigure not correctly placed in LoF

### ISSUE THREAD

**Issue by hCarlFelix** [fmarotta/kaobook#34]
I have had some problems with the LoF. Marginfigures are vertically shifted (placed inter chapter gap) in the ToF and presented in an incorrect order. 
![ToF_Problem](https://user-images.githubusercontent.com/55991448/83356312-aa281780-a365-11ea-87de-4492d341cad6.png)

By changing the kaobook's definition of marginfigure ...

```
\newsavebox{\@kao@marginfigurebox}%
\renewenvironment{marginfigure}[1][0pt]{ % The optional parameter is the vertical offset
	%\let\footnotemark\mpfootnotemark
	\FloatBarrier % Force LaTeX to place previous floats
	\mparshift{\snotez@if@nblskip{#1}{\@cdr#1\@nil\baselineskip}{#1}} % Move the figure up or down according to the offset argument
	\begin{lrbox}{\@sidenotes@marginfigurebox}%
		\begin{minipage}{\marginparwidth}%
			\captionsetup{type=figure}%
			% \centering % Better not to center margin figures
}{%
		\end{minipage}%
	\end{lrbox}%
	\marginpar{\usebox{\@sidenotes@marginfigurebox}} % Place the figure box in the margin
}
```

... back to the one of sidenotes (with minor changes) ...

```
\RenewDocumentEnvironment{marginfigure} { o } 
{
  \begin{lrbox}{\@sidenotes@marginfigurebox}
    \begin{minipage}{\marginparwidth}
      \captionsetup{type=figure}
}
{
    \end{minipage}%
  \end{lrbox}%
  \@sidenotes@placemarginal{#1}{\usebox{\@sidenotes@marginfigurebox}}
}
```
... is the issue resolved. 

I have attached a zip-file with a MWE, modified kao.sty, the output from the original kao.sty and the output from the modified kao.sty

Edit: Included an incorrect code snippet of the correction

[ToF_issue.zip](https://github.com/fmarotta/kaobook/files/4707862/ToF_issue.zip)

**Comment by fmarotta** [comment]
Thank you very much, I think this was the best thing to do! I made similar changes to `\margintable`s and `\marginlisting`s.
