### ISSUE TITLE
Small spelling error in Introduction on kaobook example

### ISSUE THREAD

**Issue by maxdrohde** [fmarotta/kaobook#35]
The word "which" is misspelled in the below text of the documentation example.

Another source of inspiration, as you may have noticed, is the 
\href{https://github.com/Tufte-LaTeX/tufte-latex}{Tufte-Latex Class}. 
The fact that the design is similar is due to the fact that it is very 
difficult to improve something >>> **wich** <<< is already so good.

**Comment by fmarotta** [comment]
Thank you, now it's fixed!
