### ISSUE TITLE
coloring chapters, sections, etc

### ISSUE THREAD

**Issue by yordiak** [fmarotta/kaobook#37]
hello,

is it possible to color referred chapters, sections, etc? for instance, it could be nice if the `\refch` produces a chapter No in colors

**Comment by fmarotta** [comment]
Hello yordiak, thank you for your patience. Yes, what you ask is possible, but you will have to edit the macros in the `stles/kaorefs.sty` package (or, alternatively, redefine them in the main.tex). The idea is to call `\hypersetup` just before the chapter number is printed, for instance, if you change
```
\newcommand{\refch}[1]{\hyperref[ch:#1]{\chaptername\xspace\ref{ch:#1}}}
```
into
```
\newcommand{\refch}[1]{\hyperref[ch:#1]{\chaptername\xspace\hypersetup{linkcolor=red}\ref{ch:#1}}}
```
you'll get something like this:
![image](https://user-images.githubusercontent.com/26001460/85932598-a1c3ed80-b8cd-11ea-8685-68fde22d7977.png)
Sometimes after the number we also print the name of the chapter (e.g. with `\nrefch`); in those case it will suffice to use \hypersetup a second time after the chapter number:
```
\newcommand{\nrefch}[1]{\hyperref[ch:#1]{\chaptername\xspace\hypersetup{linkcolor=red}\ref{ch:#1}\hypersetup{linkcolor=black} (\nameref{ch:#1})}}
```
Of course you can do the same for the other referencing commands.
