### ISSUE TITLE
index with no working hyperlinks

### ISSUE THREAD

**Issue by flaviusjose** [fmarotta/kaobook#38]
Hello,

I am trying to generate an index at the end of the document including hyperlinks on the page numbers that take me to the respective page. I indeed get the index with the correct page numbers but no working hyperlinks. 

Any help would be appreciated.

Jose Lopez

**Comment by bradyneal** [comment]
+1

Simply including the `hyperref` package normally automatically adds these hyperlinks in the index (with `imakeidx`).

I spent a bit of time commenting out hyperref stuff in kao.sty, but I was unable to get it to add the hyperlinks.

**Comment by fmarotta** [comment]
It was easier than I thought: `hyperref` is already loaded by the kaobook, but it should be loaded *after* `imakeidx`. I now included the `imakeidx` package at the very beginning of `styles/kao.sty`, and the hyperlinks work. Note that the `caption` package secretly loads `hyperref`, so `imakeidx` should also be loaded before `caption`. Thanks for reporting this, let me know if for you the links are still not OK.

**Comment by bradyneal** [comment]
Lol. Thanks @fmarotta!

**Comment by flaviusjose** [comment]
Now it is working! Thank you very much!
