### ISSUE TITLE
Option to change coloring of shaded math boxes

### ISSUE THREAD

**Issue by bradyneal** [fmarotta/kaobook#44]
There isn't an option to change the color of the shaded math boxes, is there? Right now, it looks like the color is hardcoded as `Goldenrod!45!white` in `mdftheorems.sty`.

**Comment by fmarotta** [comment]
Good point, It will be soft-coded it in the next commit.

**Comment by fmarotta** [comment]
I have added an option to the `mdftheorem` package. When you load it, you can pass it the`background=mycolour` option (replacing 'mycolour' with the actual colour, for instance, `red!35!white`). This will change the colour of all the boxes, but it is also possible to override the default colour only for some boxes. For instance, the `propositionbackground=mycolour` option will 
change the colour for propositions only. There are similar options for theorem, definition, lemma, corollary, remark, and example.

**Comment by bradyneal** [comment]
Awesome. Thanks!
