### ISSUE TITLE
Referencing mutliple sections/figures/equations/etc. at once

### ISSUE THREAD

**Issue by bradyneal** [fmarotta/kaobook#51]
Any chance there are plans for either of the following additions:

1. add functionality to the referencing commands to reference multiple labels at once
2. make the package compatible with `cleveref`

For example, when I use `cleveref`, I'm used to doing something like `\cref{sec:1,sec:2}` and getting "Sections 1 and 2" as output or doing something like `\cref{eq:1,eq:2,eq:3,eq:4}` and getting "Equations (1) to (4)" as output.

However, I believe the current solution in `kaobook` is to do `\refeq{1}, \refeq{2}, \refeq{3}, and \refeq{4}` to get "Equation 1, Equation 2, Equation 3, and Equation 4" as output or do `\refeq{1} to \refeq{4}` to get "Equation 1 to Equation 4" as output.

**Comment by fmarotta** [comment]
Yes, thanks. I included the `cleveref` package to the template. I don't know if your first point can also be considered as adressed, but now you should be able to write exactly the things you are accustomed to write. However, I still have to go through the documentation of `cleveref` and understand how to make all the customisations so that the style of the clever references blends with that of the existing references.

**Comment by fmarotta** [comment]
OK, now the behaviour of `\cref` should be pretty similar to that of the other referencing commands.

**Comment by bradyneal** [comment]
Awesome, thank you!

For anyone reading who wants the equation referencing style to match that of the `kaobook` `\refeq` command, it's easy to change. For example, if you want to change something like this
![Screen Shot 2020-08-01 at 9 53 13 AM](https://user-images.githubusercontent.com/8754873/89103146-9d638680-d3dd-11ea-9f6f-d23458fc2f76.png)
to this
![Screen Shot 2020-08-01 at 9 55 22 AM](https://user-images.githubusercontent.com/8754873/89103150-a6ecee80-d3dd-11ea-8d63-0bcaf72fc4a7.png)

then, do the following:

Change this in your template
```
% Load the package for hyperreferences
\usepackage{styles/kaorefs}
```

to this
```
% Load the package for hyperreferences
\usepackage[noabbrev]{styles/kaorefs}
\creflabelformat{equation}{#2\textup{#1}#3}
```

**Comment by fmarotta** [comment]
I think I'll make that the default behaviour.
