### ISSUE TITLE
Wide equations

### ISSUE THREAD

**Issue by bradyneal** [fmarotta/kaobook#52]
Wide figures and wide tables are great. How do we do wide equations? I currently have some equations that overflow into the margin, which gives me an ovefull \hbox warning, but more importantly, I think LaTeX tries to squish the equation because it detects it is out of space, even though it has plenty of space on the page (just not without the margin).

**Comment by fmarotta** [comment]
I have added the `widepar` and `wideequation` environments. The former can be used to typeset a paragraph in full width mode, with the text 'invading' the margin; the latter is merely a shorthand for

```
\begin{widepar}
\begin{equation}
...
\end{equation}
\end{widepar}
```

**Comment by bradyneal** [comment]
Awesome! Thanks!
