### ISSUE TITLE
Indent after equation when there is no newline between equation and paragraph

### ISSUE THREAD

**Issue by bradyneal** [fmarotta/kaobook#54]
Whenever I include text immediately after an equation, I get a small indent in the text. Example:
![Screen Shot 2020-08-04 at 1 31 33 PM](https://user-images.githubusercontent.com/8754873/89325831-58e31f80-d657-11ea-989d-39dc8b9d8239.png)

If I put a new line (in the code) between the end of the equation and the text, then this goes away, but the vertical spacing is way too large. Example:
![Screen Shot 2020-08-04 at 1 34 49 PM](https://user-images.githubusercontent.com/8754873/89325913-7b753880-d657-11ea-9169-0958442fc546.png)

Any idea how to get rid of the small indent?

**Comment by fmarotta** [comment]
I could not reproduce the problem: which equation environment are you using?

**Comment by bradyneal** [comment]
Oh, interesting. I looked into it and found out I only ran into the problem when I had an `\index` or `marginfigure` immediately between the equation and following paragraph. I figured out how to fix it with `\index{X}`: I just change `\index{X}` to `\index{X}%`. I was unable to figure out how to fix it with `marginfigure`, though (tried putting `%` in a couple places).

**Comment by fmarotta** [comment]
Very interesting. Putting more `%` definitely goes in the right direction, however, they must be added almost everywhere! I have already added them in the definition of `marginfigure` & co. but this is not enough: you will have to add a `%` after every `\end{marginfigure}`. Thus, with the latest version, a syntax similar to the following will do the trick:

```
\begin{equation}
    e^{i\pi} + 1 = 0
\end{equation}
\begin{marginfigure}
    \includegraphics{examples/documentation/images/monalisa}
    \caption{ciao}
\end{marginfigure}%
This text will not be indented.
```

By the way, this is not only a kaobook problem, it happens even in other classes, e.g.

```
\documentclass{scrbook}

\usepackage{graphicx}

\begin{document}

Hello, here the document starts.

\begin{equation}
    e^{i\pi} + 1 = 0
\end{equation}
\begin{figure}
    \includegraphics{examples/documentation/images/monalisa}
    \caption{ciao}
\end{figure}
This paragraph will have a small indent (unless the previous line in the code has a \% at the end).

\end{document}
```

**Comment by bradyneal** [comment]
Brilliant! Confirmed that it works on my end!
