### ISSUE TITLE
Can't change papersize

### ISSUE THREAD

**Issue by aradnix** [fmarotta/kaobook#58]
Hi, I'm using kaobook to adapt it to a project in which the page size is 21 x 27 cm (plus 1 cm per side to add the crop marks with the crop package that didn't work either, but I think I'll open another issue if I don't solve it).

The weird thing is that even when I declare the page size in the preamble, as I would do with KOMA Script, the resulting pdf size is still A4. I've searched through the class and package files looking for any size restrictions, but I haven't found anything so I'm here to ask.

What I have modified so far is only this:

```
\documentclass[%
fontsize=10pt,
twoside=true,
paper=22cm:28cm,
pagesize=pdftex,
% open=any,
secnumdepth=1,
chapterprefix=true,
%chapterentreydots=true,
numbers=noenddot,
%draft=true, 
%overfullrule=true, 
]{kaobook}
\usepackage[spanish,mexico]{babel}
%\usepackage[width=22truecm, height=28truecm, cam, cross, frame, axes, info, pdflatex, center]{crop}
\usepackage[spanish=mexican]{csquotes}
```

**Comment by aradnix** [comment]
I guess I found the reason, it's the configuration of the geometry paackge within the `kao.sty` file. Sorry for open the issue.

**Comment by fmarotta** [comment]
No worries, thanks for opening the issue anyway! Here is a TeX.SE post dealing with this issue, hoping that it may be helpful to you or someone else:
https://tex.stackexchange.com/questions/551390/how-do-i-set-a-paper-size-other-than-a4-in-the-kaobook-package
