### ISSUE TITLE
Changing Chapter/Section Header Fonts

### ISSUE THREAD

**Issue by jszym** [fmarotta/kaobook#60]
Hi all!

I was wondering if anyone would be able to give me any pointers on how to change the font of the Chapter or (Sub)Section fonts.

I've been able to change the body text through `setmainfont` , but can't figure out how to do so for headers. I'd like the headers to use the sans font, and the body to use the serif.

Cheers,
Joseph

**Comment by fmarotta** [comment]
Hi :)
You can use the `\addtokomafont` command, which in general works as follows:
```
\addtokomafont{element}{commands}
```
where 'element' is a part of the structure of the document (for example 'chapter', 'title', or 'section'), and 'commands' are the LaTeX commands with which the element is to be formatted. In particular, to typeset the chapter titles with a sans-serif font, you could add the following line in the preamble of your main.tex:
```
\addtokomafont{chapter}{\sffamily}
```

See also page 60 of http://texdoc.net/texmf-dist/doc/latex/koma-script/scrguien.pdf for further reference.

**Comment by jszym** [comment]
Wonderful! Thank you for the wonderful template and help!
