### ISSUE TITLE
Option for caption to appear below figure, rather than in margin

### ISSUE THREAD

**Issue by bradyneal** [fmarotta/kaobook#61]
I have a regular `figure` at the beginning of a chapter, so its caption overlaps with the margintoc. Is there a way to move the caption below the `figure` like it is in the `figure*` environment?

**Comment by fmarotta** [comment]
Good question. You can use `floatrow`'s `\RawFloats` command, which restores the default LaTeX behaviour for the float in which it is used:

```
\begin{figure}[h!]
    \RawFloats
    \centering
    \includegraphics[height=6cm]{examples/documentation/images/monalisa}
    \caption{Caption here.}
\end{figure}
```

The `\centering` becomes necessary, but if it bothers you, you can always define a new command that combines `\RawFloats` and `\centering`.

**Comment by bradyneal** [comment]
Works like a charm. Thanks again, Federico.

I didn't even realize `\centering` was automated in other environments haha.
