### ISSUE TITLE
DIscussion: release scheme

### ISSUE THREAD

**Issue by yordiak** [fmarotta/kaobook#62]
i would be reality convenient for the end-user to have a release section, where one can download different versions of your class (for some reason, someone maybe interested in an older version)

Another reason is that you can "safely" implement any experimentation you want without (potentially) breaking your current-stable class.

Therefore, I propose a release scheme of the form x.y.z, where x= stable version, y=minor fixes, z= experimental enhancements

**Comment by fmarotta** [comment]
I absolutely agree, this is also my favourite versioning scheme, but I admit that I have not been very dilegent in maintaining it so far :/ I guess one of the reasons is that there are several different files to track. Thanks for raising the problem; when the kaobook will be on CTAN, I'll probably also rearrange some things, and keeping track of the versions will become much easier.

**Comment by fmarotta** [comment]
Hi, I've just created the first official release, whimsically called "0.9.0". I also started updating the CHANGELOG.
