### ISSUE TITLE
Discussion: How are you setting up the mathematical statements?

### ISSUE THREAD

**Issue by aradnix** [fmarotta/kaobook#63]
In my experience, when we set up theorems and other mathematical statements, we can choose the style with some valid option for `\theromrestyle`.

However, reviewing the `mdftheorems.sty` file I couldn't find out how you're controlling this, so, if I have (for example) a definition that I want to appear in `plain` style but then a remark that appears with `break` style I can't find out how to make such adjustments.

what is kao's idea for achieving this?

**Comment by fmarotta** [comment]
The setup is heavily based on the `thmtools` package, which defines the `\declaretheoremstyle` command. In lines 101-164 of `mdftheorems.sty`, the various theorem styles are declared; there are 5 styles: kaoplain, kaodefinition, kaoremark, kaoassumption, and kaoexample. The names of the styles have nothing to do with the actual theorems: in principle one could write a remark using the style 'kaodefinition', for example.

Next, in line 166, the `\theoremstyle{kaoplain}` command asserts that all the theorems that will be declared afterwards will have the 'kaoplain' style. Indeed, on lines 167-215, I declare 4 theorems (theorem, proposition, lemma, corollary), all of which using the 'kaoplain' style.

In line 217, the style is changed to 'kaodefinition': from that line on, all the theorems that will be declared will have the 'kaodefinition' style. In this case, there is only one theorem with this style, and it is the 'definition' theorem.

The rest of the lines follow the same scheme. With the `\theoremstyle{style}` command, the style is changed for all the theorems that will be subsequently defined, until a new `\theoremstyle` is chosen.

Thus, to make the adjustments you want, you could move the `\declaretheorem{definition}` block under the `\theoremstyle{plain}`, and then edit the 'kaoremark' style to match the 'break' style.

I hope it is clearer now, but feel free to keep asking anyway.
