### ISSUE TITLE
Numbering of citations vs. order in the margin

### ISSUE THREAD

**Issue by smetzler** [fmarotta/kaobook#68]
In multi-citations, I noticed that the order of the citation numbers in the text does not always match the order of the margincitations. To reproduce the issue, first \sidecite{key1}, and later in the document \sidecite{key,2,key3,key1}. 

Expected outcome: [1] ... [1,2,3] in the text, and the citations in the same order in the margin.
Less favored, but potentially expected outcome: [1] ... [2,3,1] in the text, and the citations in the same order in the margin.
Actual outcome: [1] ... [1,2,3] in the text, but [1] ... [2],[3],[1] in the margin.

**Comment by fmarotta** [comment]
Hi, the latest commit should have fixed the issue.
