### ISSUE TITLE
Why GPL-licenced?

### ISSUE THREAD

**Issue by DionHo** [fmarotta/kaobook#7]
Hello,

I have a question regarding the license you are using. What is the reason you for choosing the GPL license? From what I have [read](https://opensource.stackexchange.com/a/4206), it means that I have to publish my book in source form as GPL if using this template, because it is a derived work.

In your example latex file, you are showing a CC0 license ... so I am unsure what your intention of the GPL license is. Could you please explain it to me? I really like your template and would love to use it, but I am not willing to publish the latex-sources of my work under GPL.

kind regards,
Dion

**Comment by fmarotta** [comment]
Good point.

In my original intention, the _content_ of the pdf (that is, the documentation and all of the examples) was under a CC license, while for the LaTeX part of the template I wanted a license more suitable to _code_. However, I have now realised two things: first, that I've not been clear enough in explaining my intention, and second that the GPL is too strict.

So now I think I will do as follows. I will remove the GPL license and add a MANIFEST.md file stating that the files pertaining the actual class, namely kaobook.cls and all those in the style directory, are under a LPPL ([LaTeX Project Public License](https://www.latex-project.org/lppl/)), whereas the files pertaining the example book, which only use the class files without modifying or distributing them, are under a CC license. Does this seem reasonable?

I would by glad to hear your opinion on this.
Federico

**Comment by DionHo** [comment]
I believe the solution you proposed is the way to go! Although I have to admit that I am, by no means, an expert on this legal stuff. With this solution, I would be able to use your template without any worries concerning licensing ;)

thanks for your efforts!
Dion
