### ISSUE TITLE
Cancel margin in title and abstract section of the report

### ISSUE THREAD

**Issue by atxy-blip** [fmarotta/kaobook#71]
Hi, 

I'm currently using the report template for a recent school work. Everything seems fine except that there is an undesired blank space on the right side of the title and the abstract, where the margin feature is supposed to be disabled. Could you show me a way to correct this? 

Thanks anyway.

**Comment by fmarotta** [comment]
Add `\setlength{\absrightindent}{0pt}` to the main.tex

**Comment by atxy-blip** [comment]
I managed to achieve the effect with widepar command. I think the report just looks better with full-width title section.


Thank you anyway for your kind reply.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
