### ISSUE TITLE
It seems Exercise block is missing. 

### ISSUE THREAD

**Issue by awasthi** [fmarotta/kaobook#72]
There should be an exercise block. It should be on two columns and a little bit smaller fonts

**Comment by fmarotta** [comment]
I created an environment for exercises: use it like so:
```
\begin{exercise}
...
\end{exercise}
```

You can customise it by editing the `styles/mdftheorems.sty` file, in particular see lines 154-166. Note also that there are already several packages to print exercises and solutions with style, like `exsheets` or `exercise`.
