### ISSUE TITLE
New feature: Wide Equations?

### ISSUE THREAD

**Issue by rgrunbla** [fmarotta/kaobook#73]
Hi,

first, thanks for the class, I really like it !

Do you think it would be possible / desirable to have wide environments for things like equations ?
It would behave like wide figures, tables, but with equations.

Thanks,

Rémy

**Comment by bradyneal** [comment]
See #52 :)

**Comment by rgrunbla** [comment]
Oh, well, perfect. I'll see if I can add some doc about this in the .tex :)
