### ISSUE TITLE
overfullrule=true results in overfull warnings on odd sides (chapters and pagetitles)

### ISSUE THREAD

**Issue by steven-r** [fmarotta/kaobook#79]
If I set `overfullrule=true` in the header to view overfull warnings I see a warning with 160pt for chapters and another other overfull warnings for  every page header:

![image](https://user-images.githubusercontent.com/4533301/98385348-28909000-204f-11eb-9ff7-5b05a40033fd.png)

and 

![image](https://user-images.githubusercontent.com/4533301/98385397-36461580-204f-11eb-81e1-b062ffb2a5a9.png)

Any Idea how to get rid of those warnings?

**Comment by fmarotta** [comment]
Thank you for reporting this. Unfortunately, being overfull is part of the design and cannot be avoided. The header extends into the margin and this is why LaTeX sees this as an overfull box.

**Comment by LaTeX-fetishist** [comment]
Am 20-12-06 um 15.22 schrieb Federico Marotta <notifications@github.com>:
> 
> 
> Unfortunately, being overfull is part of the design and cannot be avoided. The header extends into the margin and this is why LaTeX sees this as an overfull box.

This is bad layout.  If you want to extend material horizontally into margins you should wrap it in some horizontal box with outer width zero.  Same applies accordingly to vertical material.

Furthermore, cluttering the log with a plethora of overfull box warnings hampers the search for real pagination problems such as protruding words or hyphenation problems, e. g. in the final formatting run.


Regards,

-Moss-
--
Martin Wilhelm Leidig
Dante Member #1580

**Comment by fmarotta** [comment]
Ahh, sorry, I had no idea, forget about what I said. Thank you for the heads-up, I will try and use a box as suggested.

**Comment by fmarotta** [comment]
After the latest commit I don't get any warnings about overfull boxes (at least for chapters and headers) when compiling the documentation. Let me please know if there is something else.

**Comment by LaTeX-fetishist** [comment]
Am 20-12-08 um 21.53 schrieb Federico Marotta <notifications@github.com>:
> 
> 
> After the latest commit I don't get any warnings about overfull boxes (at least for chapters and headers) when compiling the documentation. Let me please know if there is something else.

I’ll take a look (see my remarks on free time in my other mail ;-), but no matter what: Kudos!


Regards,

-Moss-
--
Martin Wilhelm Leidig
Dante Member #1580
