### ISSUE TITLE
Long title in chapter with image do not wrap

### ISSUE THREAD

**Issue by componavt** [fmarotta/kaobook#80]
```
\setchapterimage[6cm]{path/to/image.png}
\setchapterpreamble[u]{\margintoc}
\chapter{Analysis of three aspects of modern countries: age, forms of government and ethno-horonyms}
```
If the length of the chapter title exceeds the page width, then a reader do not see the ending of this title. I do not know how to force break (newline) in this chapter title.

If I disable the image inclusion:
`%\setchapterimage[6cm]{path/to/image.png}`
then the title is wrap normally.

![long_title](https://user-images.githubusercontent.com/8916977/98935921-4a798f00-24f5-11eb-9813-42455b403fc4.png)

**Comment by fmarotta** [comment]
Hi, thanks for reporting this. Now it should be solved!
