### ISSUE TITLE
B5 format

### ISSUE THREAD

**Issue by mattialopresti** [fmarotta/kaobook#84]
Since Ph.D. theses must be print in b5paper format, I tried to convert the template into a b5paper document by changing the various geometry classes in the kao.sty file. 

As you can see in the following picture, the figure and the mini indices are cut. Is there a simple way to fix this?
![Cattura](https://user-images.githubusercontent.com/32075052/100758046-5b7c3880-33ef-11eb-8e87-360c03df2a27.PNG)

**Comment by fmarotta** [comment]
Hi,
Try the latest release, where setting the paper size is supported without having to change anything. Just pass "b5paper" as a class option and you should get the desired result.
In other words, the first line of the main.tex should be
```
\documentclass[b5paper]{kaobook}
```
This is a new feature, so I would appreciate if you could report if it works.

*Disclaimer*
I answered this issue before dealing with the older ones. Usually I prioritise the older, but it just so happened that in the past weeks I had been working exactly on the topic of this issue.

**Comment by mattialopresti** [comment]
Thank you, I'll givoe feedbacks while working on the thesis. Thank you.
