### ISSUE TITLE
Different titles for margin toc and main toc

### ISSUE THREAD

**Issue by AlexanderZeilmann** [fmarotta/kaobook#86]
Currently, when I write
```
\section[Short title]{Very long Title of the Section}
```
the ```Short title``` is used in the margin toc and the main toc, whereas the ```A very long Title of the Section``` is used in the main text.

Normally, the space I have in the margin is very constrained and I go for a really short title there.
In the normal toc I have more space and often I could fit the long section title there.

This leads to the question:
Is there a way, how I can specify a different title for the margin toc and the main toc?

**Comment by fmarotta** [comment]
Here's a way to aways display the long title in the main table of contents, while the short title is only displayed in the margintoc.

1) add these lines to the preamble of your `main.tex`:

```
\addtotoclist[kaobook]{ptoc}
\newcommand*{\listofptocname}{Contents}

\let\oldpart\part
\RenewDocumentCommand{\part}{s o m}{%
	\IfBooleanTF{#1}{%
		\oldpart*{#3}%
		\addtocontents{ptoc}{\string\contentsline {part}{\string\nonumberline {}#3}{\thepage}{part*.\thepart}}%
	}{%
		\IfValueTF{#2}{%
			\oldpart[#2]{#3}%
		}{%
			\oldpart{#3}%
		}%
		\addtocontents{ptoc}{\string\contentsline {part}{\string\numberline {\thepart}#3}{\thepage}{part.\thepart}}%
	}%
}

\let\oldchapter\chapter
\RenewDocumentCommand{\chapter}{s o m}{%
	\IfBooleanTF{#1}{%
		\oldchapter*{#3}%
		\addtocontents{ptoc}{\string\contentsline {chapter}{\string\nonumberline {}#3}{\thepage}{chapter*.\thechapter}}%
	}{%
		\IfValueTF{#2}{%
			\oldchapter[#2]{#3}%
		}{%
			\oldchapter{#3}%
		}%
		\addtocontents{ptoc}{\string\contentsline {chapter}{\string\numberline {\thechapter}#3}{\thepage}{chapter.\thechapter}}%
	}%
}

\let\oldsection\section
\RenewDocumentCommand{\section}{s o m}{%
	\IfBooleanTF{#1}{%
		\oldsection*{#3}%
		\addtocontents{ptoc}{\string\contentsline {section}{\string\nonumberline {}#3}{\thepage}{section*.\thesection}}%
	}{%
		\IfValueTF{#2}{%
			\oldsection[#2]{#3}%
		}{%
			\oldsection{#3}%
		}%
		\addtocontents{ptoc}{\string\contentsline {section}{\string\numberline {\thesection}#3}{\thepage}{section.\thesection}}%
	}%
}

\let\oldsubsection\subsection
\RenewDocumentCommand{\subsection}{s o m}{%
	\addtocontents{ptoc}{\string\contentsline {subsection}{\string\nonumberline {}#3}{\thepage}{subsection*.\thesubsection}}%
	\IfBooleanTF{#1}{%
		\oldsubsection*{#3}%
	}{%
		\IfValueTF{#2}{%
			\oldsubsection[#2]{#3}%
		}{%
			\oldsubsection{#3}%
		}%
	}%
}
```

2) instead of writing \tableofcontents, write

```
\listoftoc{ptoc}
```

3) open the `kaobook.cls` file, find the place where the macro `\chapterstylekao` is defined (which should be around line 140, depending on the version of the class), and delete the following line, which can be read towards the end of the definition of that macro:

```
\RedeclareSectionCommand[beforeskip=0cm,afterskip=10\vscale]{chapter}%
```

That should do the trick.

If instead you want to use the short title in the main table of contents sometimes, please let me know so that I can adjust my answer.

**Comment by AlexanderZeilmann** [comment]
Wow, I am seriously impressed by the amount of work you put into this template. Thank you so much!

Your solution works perfectly, so I'm closing this issue.

Maybe we find a way in the future to document questions and answers like this in one place, instead of having them distributed over GitHub issues.
