### ISSUE TITLE
Adjust size of margin

### ISSUE THREAD

**Issue by tbm** [fmarotta/kaobook#89]
I can't find anything about this in the manual... is it possible to adjust the size of the margin?

I like the idea of having a main text and some side text in the margin but it seems the margin is a bit wide by default.

**Comment by fmarotta** [comment]
Thanks, this is apparently quite a common request. I have now added a paragraph in the documentation explaining how to do it, but I will copy it here for completeness.

The easiest way is to redefine the `\marginlayout` command. This command is called internally by the higher-level `\pagelayout`, and it is responsible for setting the width of the margins and of the text. The default definition is: 

```
\renewcommand{\marginlayout}{%
    \newgeometry{
        top=27.4mm,             % height of the top margin
        bottom=27.4mm,          % height of the bottom margin
        inner=34.8mm,           % width of the inner margin
        textwidth=117mm,        % width of the text
        marginparsep=8.2mm,     % width between text and margin
        marginparwidth=39.4mm,  % width of the margin
    }%
}
```

so if you want to, say, decrease the width of the margin while increasing the width of the text, you could write in the preamble of your document something like:

```
\newcommand{\marginlayout}{%
    \newgeometry{
        top=27.4mm,
        bottom=27.4mm,
        inner=34.8mm,
        textwidth=107mm,
        marginparsep=8.2mm,
        marginparwidth=99.4mm,
    }%
}
```

where the text width has been increased by 10mm and the margin width has been decreased by 10mm.

**Comment by tbm** [comment]
Note for others reading this:

> \newcommand{\marginlayout}{%

renew, not new

Thank you, @fmarotta!  Commit 42ee0a9f9c207e1 explains it well and this works.

**Comment by tbm** [comment]
It seems there's an issue with this.

I copied the default definition into my test document.  Since this is the default definition, it shouldn't change anything:

```
  \renewcommand{\marginlayout}{%
         \newgeometry{
                 top=27.4mm,                             % height of the top margin
                 bottom=27.4mm,                  % height of the bottom margin
                 inner=34.8mm,                   % width of the inner margin
                 textwidth=107mm,                % width of the text
                 marginparsep=8.2mm,             % width between text and margin
                 marginparwidth=99.4mm,  % width of the margin
         }%
  }
```

But when I do this, the image with `\setchapterimage` gets misaligned.  See example.

[t.pdf](https://github.com/fmarotta/kaobook/files/5687840/t.pdf)

You see a misalignment on the left side.  Before, both blocks used up the whole width of the page.

**Comment by fmarotta** [comment]
Sorry, I made a lot of typos :/
the default definition should be

```
\newcommand{\marginlayout}{%
    \newgeometry{
        top=27.4mm,             % height of the top margin
        bottom=27.4mm,          % height of the bottom margin
        inner=34.8mm,           % width of the inner margin
        textwidth=107mm,        % width of the text
        marginparsep=8.2mm,     % width between text and margin
        marginparwidth=49.4mm,  % width of the margin
    }%
}
```

while the command to increase the text width by 10mm and decrease the margin width by 10mm is

```
\renewcommand{\marginlayout}{%
    \newgeometry{
        top=27.4mm,
        bottom=27.4mm,
        inner=34.8mm,
        textwidth=117mm,
        marginparsep=8.2mm,
        marginparwidth=39.4mm,
    }%
}
```

**Comment by tbm** [comment]
> Sorry, I made a lot of typos :/

Yeah, I noticed the typo in the meantime, which explains a lot of problems I was seeing.

But the image misalignment from `\setchapterimage` is still there, even if I use the default values (but use \renewcommand).

I can send a .tex example if you want.

**Comment by fmarotta** [comment]
It is due to a combination of another typo of mine and a bug in `\setchapterimage`.

The typo is that in `\newgeometry`, "inner" should be 24.8mm instead of 34.8mm as I previously wrote. I'll edit my previous comment to avoid further confusion.

The bug has been fixed in the last commit so that now even if the inner margin changes, the chapterimage should be properly aligned.

**Comment by tbm** [comment]
Ok, I changed inner to 24.8mm and now it looks good again.  I don't think inner should have an impact on `\setchapterimage` but I'm a complete newbie here.

Thank you!

**Comment by fmarotta** [comment]
I agree, I think the problem should be solved now

**Comment by fmarotta** [comment]
Yep, now everything should work. Feel free to open another issue (or reopen this one) if you spot any other problems.
