### ISSUE TITLE
Error in TeXstudio: Undefined control sequence

### ISSUE THREAD

**Issue by simoneBiomimetics** [fmarotta/kaobook#91]
Hello,
I would like to use the nice kao template to write a thesis. Compiling the code in Overleaf works fine. However, as I often work offline, I downloaded the project from Overleaf to work on it offline. 
When I compile the code using TeXstudio, I always get the following error:

Undefined control sequence. \mainmatter

Do you know where this error comes from and what I can do to solve the problem?
Thanks a lot!
Simone

**Comment by AlexanderZeilmann** [comment]
It might be this bug: https://github.com/fmarotta/kaobook/issues/74
Can you make sure, that your LaTeX packages (especially koma-script) are up to date and recheck?

**Comment by simoneBiomimetics** [comment]
Hey Alexander Zeilmann,
thanks a lot for your hint, I did not think into updating the packages... I updated MikTex and all packages and the error is gone!
Cheers,
Simone
