### ISSUE TITLE
marginfigure on wrong side when twoside=true

### ISSUE THREAD

**Issue by sjames** [fmarotta/kaobook#94]
Hi, 

First of all, this is such a great project!  I was playing around with the double sided format and realized that the marginfigures turn on on the wrong side when twoside=true.  I was wondering if anyone else has noticed this.

Regards,
Sojan

**Comment by fmarotta** [comment]
Thank you! Are you using the latest possible version? I did some fixes in recent commits and am not having this problem anymore. If you are indeed using an updated version, could you please provide a minimal working example?

**Comment by sjames** [comment]
You are right. I just updated to head and the problem is gone.  Thank you!
