### ISSUE TITLE
Enhancement / feaure request: Margintoc - limit to subsection

### ISSUE THREAD

**Issue by mithunsridharan** [fmarotta/kaobook#97]
Hi Federico,

Awesome work on this template! Kudos!
This issue is more of an enhancement / feature request.

When I use margintoc, I not only see the level 2 headings (subsection), but also the level 3 and its children (subsubsection). Is there a way to limit this only to the subsection headings?

I am currently using the following code to limit the heading levels:

**Original:** \setcounter{margintocdepth}{\subsectiontocdepth}
**Modified:** \setcounter{margintocdepth}{1}

I think there could be a much better way to set this across the entire document that I'm unaware of.

I'm new to Latex, so your help here is greatly appreciated.

Thanks in advance!

**Comment by fmarotta** [comment]
Hi, sorry for the late reply. Which version of kaobook are you using? Can you please provide a minimal working example? I can't see subsubsections in the margintoc :/

However, in general, to set the depth of the main table of contents you can use `\setcounter{tocdepth}{\subsectiontocdepth}`, while to set the depth of the margintoc you can use `\setcounter{margintocdepth}{\subsectiontocdepth}`. Here, `\subsectiontocdepth` is just an alias for `2`, the level of subsections. Setting these counters once in the preamble of your .tex file is the correct way to alter the depth of the table of contents.

**Comment by mithunsridharan** [comment]
Hi Federico,
Thanks for your update and apologies for the late reply.

Re. the kaobook version information you requested, the version I was using was 0.9.3

I updated to 0.9.5 and implemented your suggestions. Now, I have only one level in the margin TOC.

Thanks a ton for your pointers! Really appreciate it!

And, thanks from the community for developing this wonderful template!

- MS
