### ISSUE TITLE
calc error when using fontsize 11

### ISSUE THREAD

**Issue by pbienst** [fmarotta/kaobook#98]
Using this example, https://github.com/fmarotta/kaobook/tree/master/examples/minimal_book, but changing fontsize to 11pt in the documentclass gives this error:

```
main3.tex:140: Package calc Error: `.' invalid at this point.

See the calc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.140 \mainmatter
                  % Denotes the start of the main document content, resets p...


main3.tex:141: Package calc Error: `.' invalid at this point.

See the calc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.141 \setchapterstyle{kao}
                            % Choose the default chapter heading style
[1] (main3.mw)
```

**Comment by AlexanderZeilmann** [comment]
My guess what causes this bug is the following:

When using 11pt in the document class, LaTeX maps ```\normalsize``` not to ```11``` but to ```10.95```.
(see here http://tug.org/texinfohtml/latex2e.html#Font-sizes)

This is a problem in ```kaobook.cls``` in the line
```latex
	\setlength{\kao@chfsize}{\dimexpr 1mm * \f@size\relax}%
```
because ``` \f@size``` has the value 10.95, but ```\dimexpr``` expects the second factor to be an integer.

**Comment by AndreaCensi** [comment]
@AlexanderZeilmann Do you also know how to fix the problem?
